--[[                                                                           ]]--
--[[  Automatically generated code (do not edit)                               ]]--
--[[                                                                           ]]--
--[[                                                                           ]]--
--[[  Scenario                                                                 ]]--
--[[                                                                           ]]--
Scenario = {
    next_area_id = '1',
    --[[                                                                           ]]--
    --[[  Props                                                                    ]]--
    --[[                                                                           ]]--
    Props = {
    },
    --[[                                                                           ]]--
    --[[  Areas                                                                    ]]--
    --[[                                                                           ]]--
    Areas = {
        ['AREA_1'] = {
            ['rectangle'] = RECTANGLE( 5, 5, 251, 251 ),
        },
	},
    --[[                                                                           ]]--
    --[[  Markers                                                                  ]]--
    --[[                                                                           ]]--
    MasterChain = {
        ['_MASTERCHAIN_'] = {
            Markers = {
                ['AirPN01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN00 AirPN02 AirPN03 AirPN14 AirPN10' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 234.5, 3.88281, 102.5 ),
                },
                ['Defensive Point 06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 38.3984, 3.875, 118.436 ),
                },
                ['Expansion Area 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 173.5, 3.96484, 237.5 ),
                },
                ['Mass 07'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 60.5, 3.875, 130.5 ),
                },
                ['Transport Marker 04'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 127.5, 3.875, 12.5 ),
                },
                ['Hydrocarbon 01'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 54.5, 3.875, 198.5 ),
                },
                ['Mass 03'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 54.5, 3.875, 211.5 ),
                },
                ['Mass 08'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 241.5, 6.7207, 24.5 ),
                },
                ['Mass 23'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 32.5, 3.875, 73.5 ),
                },
                ['LandPN00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN01 LandPN14 LandPN05 LandPN04' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 241.5, 6.75, 14.5 ),
                },
                ['Combat Zone 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 137.5, 3.86719, 205.5 ),
                },
                ['LandPN11'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN12 LandPN10' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 180.5, 4.48828, 235.5 ),
                },
                ['Mass 17'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 224.5, 3.86719, 161.5 ),
                },
                ['Mass 19'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 161.5, 3.86719, 224.5 ),
                },
                ['AirPN03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN02 AirPN01 AirPN14 AirPN04 AirPN13 AirPN00 AirPN12' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 182.5, 3.86719, 119.5 ),
                },
                ['AirPN12'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN11 AirPN10 AirPN13 AirPN15 AirPN08 AirPN03 AirPN09' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 119.5, 3.86719, 182.5 ),
                },
                ['Rally Point 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0.0610865, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 55.9387, 3.875, 204.908 ),
                },
                ['LandPN05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN04 LandPN00 LandPN14 LandPN06 LandPN07' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 127.5, 3.875, 12.5 ),
                },
                ['LandPN03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN02 LandPN01 LandPN14 LandPN04 LandPN13' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 182.5, 3.86719, 119.5 ),
                },
                ['AirPN07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN08 AirPN06 AirPN15 AirPN09 AirPN05' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 12.5, 3.875, 127.5 ),
                },
                ['Protected Experimental Construction 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 222.978, 3.875, 122.916 ),
                },
                ['ARMY_1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 14.5, 6.74805, 241.5 ),
                },
                ['AirPN11'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN12 AirPN10 AirPN02' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 180.5, 4.48828, 235.5 ),
                },
                ['Transport Marker 03'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 22.5, 6.75, 19.5 ),
                },
                ['Mass 13'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 127.5, 3.875, 12.5 ),
                },
                ['Mass 09'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 221.5, 6.75, 10.5 ),
                },
                ['AirPN09'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN07 AirPN15 AirPN10 AirPN08 AirPN12' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 14.5, 6.74805, 241.5 ),
                },
                ['Combat Zone 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 98.5, 3.87109, 152.5 ),
                },
                ['AirPN00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN01 AirPN14 AirPN05 AirPN04 AirPN03' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 241.5, 6.75, 14.5 ),
                },
                ['AirPN14'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN00 AirPN01 AirPN05 AirPN04 AirPN03 AirPN13' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 198.5, 3.875, 55.5 ),
                },
                ['Rally Point 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 203.569, 3.875, 54.1345 ),
                },
                ['AirPN08'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN07 AirPN06 AirPN04 AirPN13 AirPN12 AirPN15 AirPN09' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 60.5, 3.875, 130.5 ),
                },
                ['LandPN14'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN00 LandPN01 LandPN05 LandPN04 LandPN03 LandPN13' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 198.5, 3.875, 55.5 ),
                },
                ['LandPN04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN05 LandPN14 LandPN03 LandPN06 LandPN08 LandPN13 LandPN00' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 130.5, 3.875, 60.5 ),
                },
                ['Defensive Point 04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 87.5, 3.86719, 90.5 ),
                },
                ['Expansion Area 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 22.5, 6.75, 18.5 ),
                },
                ['ARMY_2'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 241.5, 6.75, 14.5 ),
                },
                ['Transport Marker 05'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 115.5, 6.03125, 114.5 ),
                },
                ['Mass 01'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 10.5, 6.75, 221.5 ),
                },
                ['AirPN02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN01 AirPN03 AirPN11' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 235.5, 3.91016, 180.5 ),
                },
                ['Combat Zone 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 212.5, 3.86719, 134.5 ),
                },
                ['LandPN08'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN07 LandPN06 LandPN04 LandPN13 LandPN12 LandPN15 LandPN09' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 60.5, 3.875, 130.5 ),
                },
                ['Mass 04'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 121.5, 3.875, 236.5 ),
                },
                ['Mass 20'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 31.5, 6.75, 14.5 ),
                },
                ['Mass 22'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 14.5, 6.75, 31.5 ),
                },
                ['Mass 06'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 12.5, 3.875, 127.5 ),
                },
                ['Mass 11'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 201.5, 3.86719, 30.5 ),
                },
                ['Transport Marker 02'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 12.5, 3.875, 127.5 ),
                },
                ['Defensive Point 05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 134.272, 3.875, 23.7563 ),
                },
                ['AirPN05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN04 AirPN00 AirPN14 AirPN06 AirPN07' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 127.5, 3.875, 12.5 ),
                },
                ['Hydrocarbon 00'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 198.5, 3.875, 55.5 ),
                },
                ['Mass 21'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 74.5, 3.875, 37.5 ),
                },
                ['LandPN06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN05 LandPN07 LandPN08 LandPN04 LandPN13' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 22.5, 6.75, 19.5 ),
                },
                ['Mass 05'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 119.5, 3.86719, 182.5 ),
                },
                ['Transport Marker 01'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 235.5, 3.91016, 180.5 ),
                },
                ['Transport Marker 00'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 180.5, 4.48828, 235.5 ),
                },
                ['Expansion Area 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 238.5, 3.86719, 175.5 ),
                },
                ['LandPN01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN00 LandPN02 LandPN03 LandPN14' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 234.5, 3.88281, 102.5 ),
                },
                ['Combat Zone 04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 75.5, 3.875, 66.5 ),
                },
                ['LandPN02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN01 LandPN03' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 235.5, 3.91016, 180.5 ),
                },
                ['LandPN09'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN07 LandPN15 LandPN10 LandPN08' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 14.5, 6.74805, 241.5 ),
                },
                ['LandPN13'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN04 LandPN08 LandPN03 LandPN12 LandPN06 LandPN15 LandPN14' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 115.5, 6.03125, 114.5 ),
                },
                ['Mass 00'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 24.5, 6.7168, 241.5 ),
                },
                ['Mass 16'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 235.5, 3.91016, 180.5 ),
                },
                ['Combat Zone 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 152.5, 3.86719, 98.5 ),
                },
                ['Defensive Point 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 162.945, 3.86719, 126.799 ),
                },
                ['Mass 02'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 30.5, 3.86719, 201.5 ),
                },
                ['LandPN15'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN12 LandPN08 LandPN07 LandPN09 LandPN10 LandPN13' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 54.5, 3.875, 199.5 ),
                },
                ['Mass 10'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 211.5, 3.875, 54.5 ),
                },
                ['Defensive Point 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 120.235, 3.86719, 163.536 ),
                },
                ['Mass 12'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 234.5, 3.88281, 102.5 ),
                },
                ['Mass 18'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 180.5, 4.48828, 235.5 ),
                },
                ['LandPN12'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN11 LandPN10 LandPN13 LandPN15 LandPN08' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 119.5, 3.86719, 182.5 ),
                },
                ['Protected Experimental Construction 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 100.224, 3.875, 228.048 ),
                },
                ['LandPN10'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN11 LandPN12 LandPN09 LandPN15' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 121.5, 3.875, 236.5 ),
                },
                ['Mass 15'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 130.5, 3.875, 60.5 ),
                },
                ['AirPN15'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN12 AirPN08 AirPN07 AirPN09 AirPN10 AirPN13' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 54.5, 3.875, 199.5 ),
                },
                ['AirPN04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN05 AirPN14 AirPN03 AirPN06 AirPN08 AirPN13 AirPN00' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 130.5, 3.875, 60.5 ),
                },
                ['AirPN06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN05 AirPN07 AirPN08 AirPN04 AirPN13' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 22.5, 6.75, 19.5 ),
                },
                ['LandPN07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN08 LandPN06 LandPN15 LandPN09 LandPN05' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 12.5, 3.875, 127.5 ),
                },
                ['AirPN13'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN04 AirPN08 AirPN03 AirPN12 AirPN06 AirPN15 AirPN14' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 115.5, 6.03125, 114.5 ),
                },
                ['Mass 14'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000535846, 0 ),
                    ['position'] = VECTOR3( 182.5, 3.86719, 119.5 ),
                },
                ['AirPN10'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN11 AirPN12 AirPN09 AirPN15 AirPN01' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 121.5, 3.875, 236.5 ),
                },
                ['Rally Point 02'] = {
                    ['color'] = STRING( 'FF808000' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 51.5, 3.87109, 50.5 ),
                },
                ['Defensive Point 00'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 202.5, 6.87695, 246.5 ),
                },
                ['Defensive Point 01'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 241.479, 6.73526, 196.933 ),
                },
                ['Expansion Area 03'] = {
                    ['color'] = STRING( 'ff008080' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 37.9949, 3.875, 128.804 ),
                },
                ['Expansion Area 04'] = {
                    ['color'] = STRING( 'ff008080' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 129.5, 3.875, 37.5 ),
                },
            },
        },
    },
    Chains = {
    },
    --[[                                                                           ]]--
    --[[  Orders                                                                   ]]--
    --[[                                                                           ]]--
    next_queue_id = '1',
    Orders = {
    },
    --[[                                                                           ]]--
    --[[  Platoons                                                                 ]]--
    --[[                                                                           ]]--
    next_platoon_id = '1',
    Platoons = 
    {
    },
    --[[                                                                           ]]--
    --[[  Armies                                                                   ]]--
    --[[                                                                           ]]--
    next_army_id = '6',
    next_group_id = '7',
    next_unit_id = '112',
    Armies = 
    {
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_2'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['NEUTRAL_CIVILIAN'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                    ['WRECKAGE'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['UNIT_63'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 109.500000, 4.912109, 101.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_37'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 132.500000, 4.826172, 107.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_40'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 131.500000, 4.712891, 104.500000 },
                                Orientation = { 0.000000, 0.008727, 0.000000 },
                            },
                            ['UNIT_59'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 113.500000, 4.667969, 101.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_94'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 104.500000, 5.250000, 125.500000 },
                                Orientation = { 0.000000, 0.008727, 0.000000 },
                            },
                            ['UNIT_88'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 103.500000, 5.191406, 115.500000 },
                                Orientation = { 0.000000, 0.017453, 0.000000 },
                            },
                            ['UNIT_30'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 135.500000, 4.498047, 114.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_101'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 107.500000, 4.890625, 134.500000 },
                                Orientation = { 0.000000, -0.008727, 0.000000 },
                            },
                            ['UNIT_91'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 104.500000, 5.302734, 120.500000 },
                                Orientation = { 0.000000, 0.008727, 0.000000 },
                            },
                            ['UNIT_58'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 114.500000, 4.675781, 101.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_45'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 127.500000, 4.558594, 101.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_109'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 104.500000, 4.849609, 131.500000 },
                                Orientation = { 0.000000, 0.008727, 0.000000 },
                            },
                            ['UNIT_22'] = {
                                type = 'urc1301',
                                orders = '',
                                platoon = '',
                                Position = { 108.500000, 5.716797, 121.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_83'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 102.500000, 4.978516, 112.500000 },
                                Orientation = { 0.000000, 0.008727, 0.000000 },
                            },
                            ['UNIT_39'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 131.500000, 4.796875, 105.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_31'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 135.500000, 4.533203, 113.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_93'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 104.500000, 5.171875, 126.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_107'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 104.500000, 4.937500, 129.500000 },
                                Orientation = { 0.000000, 0.008727, 0.000000 },
                            },
                            ['UNIT_12'] = {
                                type = 'urc1301',
                                orders = '',
                                platoon = '',
                                Position = { 109.500000, 5.441406, 129.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_60'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 112.500000, 4.720703, 101.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_99'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 104.500000, 4.984375, 128.500000 },
                                Orientation = { 0.000000, 0.008727, 0.000000 },
                            },
                            ['UNIT_13'] = {
                                type = 'urc1401',
                                orders = '',
                                platoon = '',
                                Position = { 107.500000, 5.041016, 106.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_10'] = {
                                type = 'urc1101',
                                orders = '',
                                platoon = '',
                                Position = { 131.500000, 4.703125, 113.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_48'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 124.500000, 4.541016, 101.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_92'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 104.500000, 5.330078, 119.500000 },
                                Orientation = { 0.000000, 0.017453, 0.000000 },
                            },
                            ['UNIT_76'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 102.500000, 4.771484, 103.500000 },
                                Orientation = { 0.000000, 0.017453, 0.000000 },
                            },
                            ['UNIT_110'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 104.500000, 4.839844, 132.500000 },
                                Orientation = { 0.000000, 0.008727, 0.000000 },
                            },
                            ['UNIT_43'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 129.500000, 4.478516, 101.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_23'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 135.500000, 4.205078, 117.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_104'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 109.500000, 5.197266, 134.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_78'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 101.500000, 4.896484, 111.500000 },
                                Orientation = { 0.000000, 0.008727, 0.000000 },
                            },
                            ['UNIT_61'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 111.500000, 4.773438, 101.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_49'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 123.500000, 4.552734, 101.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_80'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 102.500000, 4.947266, 107.500000 },
                                Orientation = { 0.000000, 0.017453, 0.000000 },
                            },
                            ['UNIT_32'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 135.500000, 4.562500, 112.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_106'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 108.500000, 5.015625, 134.500000 },
                                Orientation = { 0.000000, 0.008727, 0.000000 },
                            },
                            ['UNIT_41'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 131.500000, 4.376953, 101.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_62'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 110.500000, 4.832031, 101.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_75'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 102.500000, 4.808594, 104.500000 },
                                Orientation = { 0.000000, 0.008727, 0.000000 },
                            },
                            ['UNIT_82'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 102.500000, 5.000000, 113.500000 },
                                Orientation = { 0.000000, 0.008727, 0.000000 },
                            },
                            ['UNIT_90'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 104.500000, 5.289063, 121.500000 },
                                Orientation = { 0.000000, 0.008727, 0.000000 },
                            },
                            ['UNIT_74'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 102.500000, 4.865234, 105.500000 },
                                Orientation = { 0.000000, 0.008727, 0.000000 },
                            },
                            ['UNIT_81'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 102.500000, 5.005859, 114.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_97'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 105.500000, 4.839844, 134.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_98'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 104.500000, 4.759766, 134.500000 },
                                Orientation = { 0.000000, 0.008727, 0.000000 },
                            },
                            ['UNIT_54'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 121.500000, 4.466797, 100.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_18'] = {
                                type = 'urc1101',
                                orders = '',
                                platoon = '',
                                Position = { 125.500000, 5.402344, 106.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_51'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 121.500000, 4.638672, 101.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_86'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 104.500000, 5.382813, 117.500000 },
                                Orientation = { 0.000000, 0.008727, 0.000000 },
                            },
                            ['UNIT_55'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 117.500000, 4.775391, 101.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_33'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 135.500000, 4.597656, 111.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_29'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 135.500000, 4.433594, 115.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_69'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 103.500000, 4.761719, 101.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_102'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 106.500000, 4.867188, 134.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_79'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 101.500000, 4.945313, 107.500000 },
                                Orientation = { 0.000000, 0.008727, 0.000000 },
                            },
                            ['UNIT_17'] = {
                                type = 'urc1101',
                                orders = '',
                                platoon = '',
                                Position = { 114.500000, 5.408203, 106.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_100'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 104.500000, 5.054688, 127.500000 },
                                Orientation = { 0.000000, 0.017453, 0.000000 },
                            },
                            ['UNIT_42'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 130.500000, 4.433594, 101.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_105'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 111.500000, 5.400391, 134.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_44'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 128.500000, 4.519531, 101.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_70'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 102.500000, 4.755859, 102.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_52'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 117.500000, 4.601563, 100.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_84'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 102.500000, 4.992188, 111.500000 },
                                Orientation = { 0.000000, 0.017453, 0.000000 },
                            },
                            ['UNIT_111'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 104.500000, 4.822266, 133.500000 },
                                Orientation = { 0.000000, 0.008727, 0.000000 },
                            },
                            ['UNIT_71'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 131.500000, 4.609375, 103.500000 },
                                Orientation = { 0.000000, 0.008727, 0.000000 },
                            },
                            ['UNIT_57'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 115.500000, 4.734375, 101.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['GROUP_2'] = GROUP {
                                orders = '',
                                platoon = '',
                                Units = {
                                },
                            },
                            ['UNIT_50'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 122.500000, 4.582031, 101.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_108'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 104.500000, 4.882813, 130.500000 },
                                Orientation = { 0.000000, 0.008727, 0.000000 },
                            },
                            ['UNIT_66'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 106.500000, 4.906250, 101.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_73'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 102.500000, 4.904297, 106.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_36'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 133.500000, 4.626953, 108.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_95'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 104.500000, 5.246094, 124.500000 },
                                Orientation = { 0.000000, 0.008727, 0.000000 },
                            },
                            ['UNIT_68'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 104.500000, 4.806641, 101.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_65'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 107.500000, 4.953125, 101.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_56'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 116.500000, 4.763672, 101.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_47'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 125.500000, 4.552734, 101.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_67'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 105.500000, 4.857422, 101.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_34'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 135.500000, 4.613281, 110.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_64'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 108.500000, 4.966797, 101.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_87'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 104.500000, 5.353516, 116.500000 },
                                Orientation = { 0.000000, 0.008727, 0.000000 },
                            },
                            ['UNIT_96'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 104.500000, 5.246094, 123.500000 },
                                Orientation = { 0.000000, 0.017453, 0.000000 },
                            },
                            ['UNIT_103'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 110.500000, 5.322266, 134.500000 },
                                Orientation = { 0.000000, -0.008727, 0.000000 },
                            },
                            ['UNIT_28'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 135.500000, 4.330078, 116.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_38'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 131.500000, 4.873047, 106.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_35'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 134.500000, 4.585938, 109.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_46'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 126.500000, 4.570313, 101.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_85'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 104.500000, 5.371094, 118.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_89'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 104.500000, 5.273438, 122.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_72'] = {
                                type = 'urb5101',
                                orders = '',
                                platoon = '',
                                Position = { 131.500000, 4.490234, 102.500000 },
                                Orientation = { 0.000000, 0.017453, 0.000000 },
                            },
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_1'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
    },
}
