--[[                                                                           ]]--
--[[  Automatically generated code (do not edit)                               ]]--
--[[                                                                           ]]--
--[[                                                                           ]]--
--[[  Scenario                                                                 ]]--
--[[                                                                           ]]--
Scenario = {
    next_area_id = '1',
    --[[                                                                           ]]--
    --[[  Props                                                                    ]]--
    --[[                                                                           ]]--
    Props = {
    },
    --[[                                                                           ]]--
    --[[  Areas                                                                    ]]--
    --[[                                                                           ]]--
    Areas = {
        ['AREA_1'] = {
            ['rectangle'] = RECTANGLE( 5, 5, 251, 251 ),
        },
    },
    --[[                                                                           ]]--
    --[[  Markers                                                                  ]]--
    --[[                                                                           ]]--
    MasterChain = {
        ['_MASTERCHAIN_'] = {
            Markers = {
                ['Transport Marker 07'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 106.5, 17.5781, 146.5 ),
                },
                ['AirPN01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN00 AirPN02 AirPN03 AirPN07 AirPN08 AirPN16 AirPN14' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 106.5, 17.5859, 106.5 ),
                },
                ['Defensive Point 06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 109.784, 17.5781, 147.71 ),
                },
                ['Hydrocarbon 03'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 19.5, 18.5293, 83.5 ),
                },
                ['Mass 27'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 52.5, 17.4805, 15.5 ),
                },
                ['Mass 07'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 157.5, 17.4668, 224.5 ),
                },
                ['Combat Zone 04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 231.917, 18.5078, 185.933 ),
                },
                ['Hydrocarbon 01'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 235.5, 18.4629, 172.5 ),
                },
                ['Mass 03'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 223.5, 17.4688, 94.5 ),
                },
                ['Defensive Point 11'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 174.884, 17.4766, 172.496 ),
                },
                ['Mass 20'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 117.5, 17.5781, 117.5 ),
                },
                ['Mass 08'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 41.5, 17.4766, 151.5 ),
                },
                ['LandPN16'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN03 LandPN07 LandPN12 LandPN11' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 206.5, 17.4707, 146.5 ),
                },
                ['LandPN00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN03 LandPN01 LandPN10 LandPN11 LandPN15' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 95.5, 17.4688, 37.5 ),
                },
                ['LandPN03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN02 LandPN00 LandPN12 LandPN11 LandPN16' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 222.5, 17.4609, 80.5 ),
                },
                ['Mass 05'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 144.5, 17.623, 206.5 ),
                },
                ['AirPN02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN00 AirPN01 AirPN04 AirPN07 AirPN06 AirPN14 AirPN12' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 146.5, 17.5781, 106.5 ),
                },
                ['AirPN04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN03 AirPN00 AirPN02 AirPN06 AirPN05 AirPN12 AirPN10' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 146.5, 17.5781, 146.5 ),
                },
                ['LandPN07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN16' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 228.5, 18.457, 182.5 ),
                },
                ['AirPN05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN11 AirPN12 AirPN06 AirPN08 AirPN04 AirPN03 AirPN20 AirPN10' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 161.5, 17.4688, 210.5 ),
                },
                ['LandPN11'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN12 LandPN04 LandPN10 LandPN00 LandPN03 LandPN15 LandPN16' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 146.5, 17.5781, 106.5 ),
                },
                ['AirPN15'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN16 AirPN07 AirPN18' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 52.5, 17.4805, 15.5 ),
                },
                ['Combat Zone 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 173.5, 17.5703, 148.5 ),
                },
                ['Rally Point 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 195.788, 17.502, 113.667 ),
                },
                ['Mass 17'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 180.5, 17.5723, 136.5 ),
                },
                ['AirPN20'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN10 AirPN05 AirPN11 AirPN00' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 126.5, 22.6914, 236.5 ),
                },
                ['AirPN13'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN14 AirPN06 AirPN19' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 241.5, 17.457, 46.5 ),
                },
                ['AirPN03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN04 AirPN00 AirPN01 AirPN08 AirPN05 AirPN10 AirPN16' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 106.5, 17.5781, 146.5 ),
                },
                ['Expansion Area 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 35.5, 17.6133, 88.5 ),
                },
                ['Mass 33'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 138.5, 17.5781, 117.5 ),
                },
                ['Mass 00'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 222.5, 17.4688, 66.5 ),
                },
                ['Mass 14'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 109.5, 17.4727, 43.5 ),
                },
                ['AirPN18'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN00 AirPN14 AirPN07 AirPN15' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 126.5, 22.0215, 15.5 ),
                },
                ['AirPN12'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN11 AirPN05 AirPN19 AirPN04 AirPN02' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 228.5, 18.457, 182.5 ),
                },
                ['Mass 25'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 208.5, 17.4746, 240.5 ),
                },
                ['Rally Point 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 60.8092, 17.5781, 136.661 ),
                },
                ['Protected Experimental Construction 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 195.788, 17.4668, 234.61 ),
                },
                ['LandPN05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN14' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 26.5, 18.3496, 72.5 ),
                },
                ['AirPN10'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN09 AirPN20 AirPN08 AirPN03 AirPN04 AirPN05' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 70.5, 18.4629, 229.5 ),
                },
                ['AirPN07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN16 AirPN15 AirPN08 AirPN06 AirPN01 AirPN02 AirPN18 AirPN14' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 95.5, 17.4688, 37.5 ),
                },
                ['Transport Marker 05'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 106.5, 17.5859, 106.5 ),
                },
                ['AirPN17'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN00 AirPN08 AirPN09 AirPN16' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 16.5, 24.2617, 126.5 ),
                },
                ['Combat Zone 07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 84.9993, 18.125, 221.767 ),
                },
                ['AirPN11'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN12 AirPN05 AirPN20' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 208.5, 17.4746, 240.5 ),
                },
                ['Transport Marker 03'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 26.5, 18.3496, 72.5 ),
                },
                ['Combat Zone 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 155.5, 17.5879, 88.5 ),
                },
                ['Defensive Point 09'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 86.192, 17.4844, 76.3379 ),
                },
                ['Mass 09'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 53.5, 17.4766, 165.5 ),
                },
                ['AirPN09'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN10 AirPN08 AirPN17' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 15.5, 17.4746, 208.5 ),
                },
                ['Rally Point 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 119.34, 17.5625, 59.9136 ),
                },
                ['LandPN08'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN13' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 70.5, 18.4629, 229.5 ),
                },
                ['Mass 26'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 15.5, 17.4746, 208.5 ),
                },
                ['Defensive Point 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 155.968, 17.469, 48.9564 ),
                },
                ['AirPN00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN01 AirPN02 AirPN03 AirPN04 AirPN17 AirPN20 AirPN19 AirPN18' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 126.5, 17.5938, 126.5 ),
                },
                ['AirPN14'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN13 AirPN06 AirPN18 AirPN02 AirPN01 AirPN07' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 184.5, 18.3535, 27.5 ),
                },
                ['Transport Marker 06'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 146.5, 17.5781, 106.5 ),
                },
                ['AirPN08'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN10 AirPN09 AirPN07 AirPN05 AirPN01 AirPN03 AirPN17 AirPN16' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 38.5, 17.4688, 165.5 ),
                },
                ['LandPN14'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN01 LandPN05 LandPN10 LandPN09' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 46.5, 17.459, 106.5 ),
                },
                ['Mass 02'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 207.5, 17.4688, 80.5 ),
                },
                ['Combat Zone 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 100.5, 17.5703, 167.5 ),
                },
                ['AirPN16'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN15 AirPN07 AirPN17 AirPN01 AirPN03 AirPN08' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 26.5, 18.3496, 72.5 ),
                },
                ['Expansion Area 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 86.5, 17.7715, 219.5 ),
                },
                ['LandPN04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN12 LandPN11 LandPN09 LandPN10' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 126.5, 17.5938, 126.5 ),
                },
                ['Mass 31'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 70.5, 18.4629, 229.5 ),
                },
                ['Defensive Point 10'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 75.7404, 17.4844, 173.093 ),
                },
                ['Expansion Area 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 215.5, 17.4531, 166.5 ),
                },
                ['Mass 30'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 26.5, 18.3496, 72.5 ),
                },
                ['Defensive Point 04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 146.813, 17.5781, 106.201 ),
                },
                ['Combat Zone 05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 177.272, 18.1953, 29.4573 ),
                },
                ['Mass 12'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 103.5, 17.5195, 24.5 ),
                },
                ['ARMY_1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 222.5, 17.4609, 80.5 ),
                },
                ['Mass 32'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 139.5, 17.5879, 136.5 ),
                },
                ['Defensive Point 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 47.269, 17.4823, 97.4482 ),
                },
                ['ARMY_2'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 38.5, 17.4688, 165.5 ),
                },
                ['ARMY_4'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 161.5, 17.4688, 210.5 ),
                },
                ['Mass 01'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 237.5, 17.4531, 80.5 ),
                },
                ['AirPN06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN14 AirPN13 AirPN05 AirPN07 AirPN04 AirPN02 AirPN19' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 222.5, 17.4609, 80.5 ),
                },
                ['ARMY_3'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 95.5, 17.4688, 37.5 ),
                },
                ['Mass 19'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 73.5, 17.6074, 120.5 ),
                },
                ['Mass 04'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 165.5, 17.4766, 194.5 ),
                },
                ['AirPN19'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN00 AirPN06 AirPN13 AirPN12' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 236.5, 20.127, 126.5 ),
                },
                ['Mass 28'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 184.5, 18.3535, 27.5 ),
                },
                ['Mass 06'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 176.5, 17.4648, 213.5 ),
                },
                ['Mass 11'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 25.5, 17.4492, 163.5 ),
                },
                ['Transport Marker 02'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 70.5, 18.4629, 229.5 ),
                },
                ['Defensive Point 05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 147.112, 17.582, 143.529 ),
                },
                ['Combat Zone 06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 31.2467, 18.0137, 76.9373 ),
                },
                ['Hydrocarbon 00'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 84.5, 18.5781, 236.5 ),
                },
                ['Mass 21'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 119.5, 17.5898, 138.5 ),
                },
                ['LandPN06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN15' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 184.5, 18.3535, 27.5 ),
                },
                ['Defensive Point 08'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 175.183, 17.5156, 85.2969 ),
                },
                ['Transport Marker 01'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 228.5, 18.457, 182.5 ),
                },
                ['Mass 13'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 82.5, 17.4688, 31.5 ),
                },
                ['Expansion Area 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 167.5, 17.4551, 39.5 ),
                },
                ['LandPN01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN02 LandPN00 LandPN09 LandPN10 LandPN14' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 38.5, 17.4688, 165.5 ),
                },
                ['Protected Experimental Construction 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 21.9879, 17.4668, 196.386 ),
                },
                ['LandPN02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN12 LandPN01 LandPN03 LandPN09 LandPN13' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 161.5, 17.4688, 210.5 ),
                },
                ['LandPN09'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN10 LandPN04 LandPN12 LandPN02 LandPN01 LandPN13 LandPN14' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 106.5, 17.5781, 146.5 ),
                },
                ['Transport Marker 08'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 146.5, 17.5781, 146.5 ),
                },
                ['Mass 16'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 137.5, 17.5703, 74.5 ),
                },
                ['Rally Point 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 130.688, 17.6113, 190.115 ),
                },
                ['Combat Zone 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 87.5, 17.5703, 104.5 ),
                },
                ['LandPN12'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN02 LandPN11 LandPN04 LandPN09 LandPN03 LandPN16 LandPN13' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 146.5, 17.5781, 146.5 ),
                },
                ['Mass 24'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 241.5, 17.457, 46.5 ),
                },
                ['Protected Experimental Construction 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 241.18, 17.4727, 52.4474 ),
                },
                ['Mass 10'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 40.5, 17.4688, 180.5 ),
                },
                ['Transport Marker 04'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 184.5, 18.3535, 27.5 ),
                },
                ['LandPN13'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN08 LandPN02 LandPN09 LandPN12' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 106.5, 17.4746, 206.5 ),
                },
                ['Mass 18'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 119.5, 17.5703, 179.5 ),
                },
                ['Large Expansion Area 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ffff0080' ),
                    ['type'] = STRING( 'Large Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000134945, 0 ),
                    ['position'] = VECTOR3( 128.237, 17.5938, 128.616 ),
                },
                ['Protected Experimental Construction 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 62.3014, 17.4844, 16.0144 ),
                },
                ['LandPN10'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN09 LandPN04 LandPN11 LandPN00 LandPN01 LandPN14 LandPN15' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 106.5, 17.5859, 106.5 ),
                },
                ['Mass 15'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 87.5, 17.4766, 51.5 ),
                },
                ['Defensive Point 07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 106.2, 17.5859, 110.681 ),
                },
                ['Hydrocarbon 02'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 172.5, 18.4961, 20.5 ),
                },
                ['Mass 29'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 228.5, 18.457, 182.5 ),
                },
                ['Defensive Point 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 102.602, 17.4766, 204.612 ),
                },
                ['LandPN15'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN00 LandPN06 LandPN11 LandPN10' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 146.5, 17.4258, 46.5 ),
                },
                ['Defensive Point 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 205.056, 17.4766, 153.941 ),
                },
                ['Transport Marker 00'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 126.5, 17.5938, 126.5 ),
                },
            },
        },
    },
    Chains = {
    },
    --[[                                                                           ]]--
    --[[  Orders                                                                   ]]--
    --[[                                                                           ]]--
    next_queue_id = '1',
    Orders = {
    },
    --[[                                                                           ]]--
    --[[  Platoons                                                                 ]]--
    --[[                                                                           ]]--
    next_platoon_id = '1',
    Platoons = 
    {
    },
    --[[                                                                           ]]--
    --[[  Armies                                                                   ]]--
    --[[                                                                           ]]--
    next_army_id = '8',
    next_group_id = '2',
    next_unit_id = '108',
    Armies = 
    {
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_3'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_1'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_4'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_9'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['UNIT_105'] = {
                                type = 'ueb1201',
                                orders = '',
                                platoon = '',
                                Position = { 134.500000, 17.593750, 129.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_106'] = {
                                type = 'ueb2104',
                                orders = '',
                                platoon = '',
                                Position = { 127.500000, 17.593750, 127.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_107'] = {
                                type = 'ueb3101',
                                orders = '',
                                platoon = '',
                                Position = { 130.500000, 17.593750, 131.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_100'] = {
                                type = 'ueb2101',
                                orders = '',
                                platoon = '',
                                Position = { 127.500000, 17.593750, 132.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_66'] = {
                                type = 'ueb2101',
                                orders = '',
                                platoon = '',
                                Position = { 127.500000, 17.593750, 121.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['NEUTRAL_CIVILIAN'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['UNIT_5'] = {
                                type = 'uec1301',
                                orders = '',
                                platoon = '',
                                Position = { 133.500000, 17.585938, 112.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_57'] = {
                                type = 'uec1301',
                                orders = '',
                                platoon = '',
                                Position = { 121.500000, 17.578125, 112.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_37'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 111.500000, 17.593750, 109.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_40'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 106.500000, 17.613281, 116.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_44'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 148.500000, 17.591797, 139.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_59'] = {
                                type = 'uec1501',
                                orders = '',
                                platoon = '',
                                Position = { 113.500000, 17.578125, 134.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_77'] = {
                                type = 'uec1201',
                                orders = '',
                                platoon = '',
                                Position = { 143.500000, 17.578125, 121.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_41'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 106.500000, 17.591797, 115.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_75'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 128.500000, 17.593750, 121.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_74'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 127.500000, 17.593750, 120.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_42'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 107.500000, 17.593750, 115.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_47'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 144.500000, 17.587891, 144.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_45'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 143.500000, 17.587891, 145.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_33'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 116.113670, 17.610853, 149.841675 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_39'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 112.500000, 17.603516, 109.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_38'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 111.500000, 17.601563, 110.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_52'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 140.500000, 17.593750, 108.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_12'] = {
                                type = 'uec1101',
                                orders = '',
                                platoon = '',
                                Position = { 131.500000, 17.580078, 139.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_60'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 139.500000, 17.593750, 107.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_99'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 127.500000, 17.593750, 133.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_58'] = {
                                type = 'uec1501',
                                orders = '',
                                platoon = '',
                                Position = { 109.500000, 17.578125, 128.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_53'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 145.935043, 17.587137, 111.576790 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_51'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 146.935043, 17.578711, 111.576790 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_8'] = {
                                type = 'uec1101',
                                orders = '',
                                platoon = '',
                                Position = { 125.500000, 17.593750, 139.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_49'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 146.935043, 17.614017, 112.576790 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_15'] = {
                                type = 'uec1401',
                                orders = '',
                                platoon = '',
                                Position = { 134.500000, 17.593750, 122.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_48'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 147.500000, 17.593750, 139.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_56'] = {
                                type = 'uec1401',
                                orders = '',
                                platoon = '',
                                Position = { 120.500000, 17.593750, 122.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_46'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 148.500000, 17.613281, 138.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_76'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 126.500000, 17.593750, 121.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_34'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 117.113670, 17.798931, 149.841675 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_35'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 116.113670, 17.601225, 148.841675 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_16'] = {
                                type = 'uec1501',
                                orders = '',
                                platoon = '',
                                Position = { 113.500000, 17.578125, 123.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_9'] = {
                                type = 'uec1301',
                                orders = '',
                                platoon = '',
                                Position = { 127.500000, 17.578125, 110.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_13'] = {
                                type = 'uec1201',
                                orders = '',
                                platoon = '',
                                Position = { 143.500000, 17.580078, 130.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_54'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 140.500000, 17.591797, 107.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_31'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 109.500000, 17.603516, 142.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_43'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 144.500000, 17.583984, 145.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_36'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 110.500000, 17.599609, 143.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_32'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 109.500000, 17.585938, 143.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_97'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 126.500000, 17.593750, 132.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_98'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 128.500000, 17.593750, 132.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_2'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
    },
}
