--[[                                                                           ]]--
--[[  Automatically generated code (do not edit)                               ]]--
--[[                                                                           ]]--
--[[                                                                           ]]--
--[[  Scenario                                                                 ]]--
--[[                                                                           ]]--
Scenario = {
    next_area_id = '1',
    --[[                                                                           ]]--
    --[[  Props                                                                    ]]--
    --[[                                                                           ]]--
    Props = {
    },
    --[[                                                                           ]]--
    --[[  Areas                                                                    ]]--
    --[[                                                                           ]]--
    Areas = {
        ['AREA_1'] = {
            ['rectangle'] = RECTANGLE( 5, 5, 251, 251 ),
        },
    },
    --[[                                                                           ]]--
    --[[  Markers                                                                  ]]--
    --[[                                                                           ]]--
    MasterChain = {
        ['_MASTERCHAIN_'] = {
            Markers = {
                ['AirPN01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN13 AirPN16 AirPN07 AirPN05' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 152.5, 20.4922, 230.5 ),
                },
                ['Defensive Point13'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 147.5, 23.6035, 15.5 ),
                },
                ['Rally Point 06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 160.518, 18.686, 112.236 ),
                },
                ['Mass 00'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 22.3641, 24.977, 135.148 ),
                },
                ['Mass15'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 217.5, 18.709, 183.5 ),
                },
                ['Hydrocarbon26'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 99.5, 23.3262, 206.5 ),
                },
                ['Expansion Area25'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 155.5, 19.2109, 97.5 ),
                },
                ['Defensive Point7'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 111.5, 23.8906, 215.5 ),
                },
                ['Defensive Point8'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 47.5, 24.8711, 147.5 ),
                },
                ['Rally Point 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 221.5, 26.4297, 43.5 ),
                },
                ['Mass10'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 152.5, 20.4141, 211.5 ),
                },
                ['Defensive Point15'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 206.5, 20.2266, 245.5 ),
                },
                ['Mass3'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 113.5, 20.4727, 36.5 ),
                },
                ['Rally Point 04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 47.25, 21.1107, 121.458 ),
                },
                ['AirPN15'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN00 AirPN14 AirPN03 AirPN06 AirPN20' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 144.5, 24.0039, 42.5 ),
                },
                ['LandPN07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN19 LandPN01 LandPN16 LandPN02 LandPN17' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 32.5, 26.9258, 243.5 ),
                },
                ['Defensive Point6'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 82.5, 18.4473, 82.5 ),
                },
                ['AirPN04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN08 AirPN00 AirPN12 AirPN14 AirPN17' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 40.5, 18.6914, 71.5 ),
                },
                ['Defensive Point16'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 51.5, 20.2363, 13.5 ),
                },
                ['AirPN06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN00 AirPN20 AirPN15 AirPN03 AirPN18' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 223.5, 26.9688, 19.5 ),
                },
                ['AirPN20'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN18 AirPN09 AirPN06 AirPN15' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 248.5, 26.7324, 98.5 ),
                },
                ['AirPN13'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN10 AirPN01 AirPN16 AirPN02 AirPN05 AirPN11 AirPN12 AirPN18' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 146.5, 19.7637, 197.5 ),
                },
                ['LandPN19'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN17 LandPN08 LandPN07 LandPN16' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 7.5, 26.9434, 157.5 ),
                },
                ['Mass23'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 162.5, 18.7031, 120.5 ),
                },
                ['Combat Zone21'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 230.5, 18.709, 208.5 ),
                },
                ['Mass2'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 90.5, 20.4746, 22.5 ),
                },
                ['Mass24'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 93.5, 18.6973, 136.5 ),
                },
                ['AirPN18'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN20 AirPN09 AirPN11 AirPN03 AirPN06 AirPN05 AirPN13' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 206.5, 24.8984, 108.5 ),
                },
                ['AirPN12'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN02 AirPN17 AirPN10 AirPN14 AirPN13 AirPN04' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 93.5, 18.6973, 136.5 ),
                },
                ['LandPN11'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN18 LandPN03 LandPN10 LandPN13 LandPN14 LandPN05' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 162.5, 18.7031, 120.5 ),
                },
                ['Rally Point 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 146.214, 19.7832, 197.573 ),
                },
                ['Rally Point 05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 214.35, 22.3744, 135.46 ),
                },
                ['LandPN05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN09 LandPN01 LandPN13 LandPN11 LandPN18' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 217.5, 18.709, 183.5 ),
                },
                ['LandPN03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN18 LandPN11 LandPN15 LandPN14 LandPN06 LandPN10' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 162.5, 20.5684, 76.5 ),
                },
                ['AirPN07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN19 AirPN01 AirPN16 AirPN02 AirPN17' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 32.5, 26.9258, 243.5 ),
                },
                ['Protected Experimental Construction 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 78.4343, 20.4922, 11.2532 ),
                },
                ['Expansion Area24'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 24.5, 26.9355, 233.5 ),
                },
                ['Defensive Point14'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 105.5, 23.8711, 245.5 ),
                },
                ['Mass4'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 103.5, 20.3809, 44.5 ),
                },
                ['Transport Marker 03'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 223.5, 26.9688, 19.5 ),
                },
                ['LandPN17'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN19 LandPN08 LandPN12 LandPN02 LandPN07 LandPN04 LandPN14' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 47.5, 24.8711, 147.5 ),
                },
                ['LandPN16'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN13 LandPN01 LandPN02 LandPN07 LandPN19' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 111.5, 23.8906, 215.5 ),
                },
                ['LandPN15'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN00 LandPN14 LandPN03 LandPN06 LandPN20' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 144.5, 24.0039, 42.5 ),
                },
                ['Defensive Point11'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 209.5, 25.8457, 43.5 ),
                },
                ['Mass9'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 142.5, 20.4746, 219.5 ),
                },
                ['Combat Zone17'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 111.5, 18.6602, 153.5 ),
                },
                ['LandPN14'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN00 LandPN10 LandPN15 LandPN03 LandPN12 LandPN11 LandPN04 LandPN17' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 110.5, 19.8262, 57.5 ),
                },
                ['LandPN13'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN10 LandPN01 LandPN16 LandPN02 LandPN05 LandPN11 LandPN12 LandPN18' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 146.5, 19.7637, 197.5 ),
                },
                ['Defensive Point12'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 42.5, 26.5801, 212.5 ),
                },
                ['AirPN14'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN00 AirPN10 AirPN15 AirPN03 AirPN12 AirPN11 AirPN04 AirPN17' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 110.5, 19.8262, 57.5 ),
                },
                ['Rally Point 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 110.681, 19.8359, 57.5315 ),
                },
                ['AirPN08'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN17 AirPN19 AirPN04' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 20.5, 24.8711, 125.5 ),
                },
                ['Mass21'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 223.5, 26.9688, 19.5 ),
                },
                ['Expansion Area27'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 231.5, 24.625, 131.5 ),
                },
                ['Expansion Area26'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 102.5, 19.1328, 158.5 ),
                },
                ['Mass19'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 22.5, 24.7598, 122.5 ),
                },
                ['LandPN08'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN17 LandPN19 LandPN04' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 20.5, 24.8711, 125.5 ),
                },
                ['LandPN04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN08 LandPN00 LandPN12 LandPN14 LandPN17' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 40.5, 18.6914, 71.5 ),
                },
                ['LandPN20'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN18 LandPN09 LandPN06 LandPN15' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 248.5, 26.7324, 98.5 ),
                },
                ['Mass17'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 239.5, 26.9414, 42.5 ),
                },
                ['Expansion Area28'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 22.5, 24.8301, 128.5 ),
                },
                ['Transport Marker 06'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 162.5, 20.5684, 76.5 ),
                },
                ['Transport Marker 05'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 94.5, 20.6426, 181.5 ),
                },
                ['Defensive Point30'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 214.5, 22.3984, 134.5 ),
                },
                ['Defensive Point10'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 144.5, 23.916, 41.5 ),
                },
                ['Transport Marker 00'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 40.5, 18.6914, 71.5 ),
                },
                ['Mass20'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 233.5, 24.7051, 139.5 ),
                },
                ['Mass13'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 160.5, 20.3652, 219.5 ),
                },
                ['ARMY_2'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 152.5, 20.4922, 230.5 ),
                },
                ['Hydrocarbon25'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 156.5, 23.3262, 48.5 ),
                },
                ['Mass 01'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 232.612, 24.9243, 122.653 ),
                },
                ['AirPN02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN12 AirPN16 AirPN17 AirPN13 AirPN07 AirPN10' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 94.5, 20.6426, 181.5 ),
                },
                ['AirPN16'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN13 AirPN01 AirPN02 AirPN07 AirPN19' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 111.5, 23.8906, 215.5 ),
                },
                ['LandPN00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN14 LandPN15 LandPN06 LandPN04 ' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 103.5, 20.4922, 25.5 ),
                },
                ['Mass22'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 32.5, 26.9258, 243.5 ),
                },
                ['AirPN19'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN17 AirPN08 AirPN07 AirPN16' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 7.5, 26.9434, 157.5 ),
                },
                ['AirPN05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN09 AirPN01 AirPN13 AirPN11 AirPN18' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 217.5, 18.709, 183.5 ),
                },
                ['Mass8'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 111.5, 20.4922, 22.5 ),
                },
                ['AirPN00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN14 AirPN15 AirPN06 AirPN04 ' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 103.5, 20.4922, 25.5 ),
                },
                ['Transport Marker 02'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 32.5, 26.9258, 243.5 ),
                },
                ['AirPN03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN18 AirPN11 AirPN15 AirPN14 AirPN06 AirPN10' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 162.5, 20.5684, 76.5 ),
                },
                ['AirPN09'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN18 AirPN20 AirPN05' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 234.5, 24.8223, 132.5 ),
                },
                ['AirPN10'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN14 AirPN13 AirPN12 AirPN11 AirPN02 AirPN03' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 127.5, 17.5, 127.5 ),
                },
                ['AirPN11'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN18 AirPN03 AirPN10 AirPN13 AirPN14 AirPN05' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 162.5, 18.7031, 120.5 ),
                },
                ['LandPN06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN00 LandPN20 LandPN15 LandPN03 LandPN18' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 223.5, 26.9688, 19.5 ),
                },
                ['Mass7'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 94.5, 20.2715, 36.5 ),
                },
                ['Transport Marker 01'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 217.5, 18.709, 183.5 ),
                },
                ['LandPN02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN12 LandPN16 LandPN17 LandPN13 LandPN07 LandPN10' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 94.5, 20.6426, 181.5 ),
                },
                ['Transport Marker 04'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 127.5, 17.5, 127.5 ),
                },
                ['LandPN01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN13 LandPN16 LandPN07 LandPN05' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 152.5, 20.4922, 230.5 ),
                },
                ['Combat Zone18'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 141.5, 18.5156, 107.5 ),
                },
                ['Defensive Point9'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 206.5, 24.8984, 108.5 ),
                },
                ['LandPN09'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN18 LandPN20 LandPN05' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 234.5, 24.8223, 132.5 ),
                },
                ['LandPN18'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN20 LandPN09 LandPN11 LandPN03 LandPN06 LandPN05 LandPN13' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 206.5, 24.8984, 108.5 ),
                },
                ['AirPN17'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN19 AirPN08 AirPN12 AirPN02 AirPN07 AirPN04 AirPN14' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 47.5, 24.8711, 147.5 ),
                },
                ['Mass1'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 103.5, 20.4922, 12.5 ),
                },
                ['ARMY_1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 103.5, 20.4922, 25.5 ),
                },
                ['LandPN12'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN02 LandPN17 LandPN10 LandPN14 LandPN13 LandPN04' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 93.5, 18.6973, 136.5 ),
                },
                ['Combat Zone20'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 64.5, 25.6777, 199.5 ),
                },
                ['Rally Point 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 39.2828, 26.7649, 224.265 ),
                },
                ['Mass14'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 144.5, 20.4922, 233.5 ),
                },
                ['Defensive Point29'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 42.5, 22.125, 122.5 ),
                },
                ['Mass12'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 152.5, 20.4922, 243.5 ),
                },
                ['Combat Zone22'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 23.5, 18.7109, 48.5 ),
                },
                ['Mass18'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 18.5, 26.9492, 220.5 ),
                },
                ['Protected Experimental Construction 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 182.342, 20.4922, 245.345 ),
                },
                ['LandPN10'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN14 LandPN13 LandPN12 LandPN11 LandPN02 LandPN03' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000269294, 0 ),
                    ['position'] = VECTOR3( 127.5, 17.5, 127.5 ),
                },
                ['Defensive Point4'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 177.5, 18.4199, 171.5 ),
                },
                ['Rally Point 07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 99.9285, 18.6199, 143.353 ),
                },
                ['Mass6'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 162.5, 20.5684, 76.5 ),
                },
                ['Mass16'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 94.5, 20.6426, 181.5 ),
                },
                ['Combat Zone19'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 200.5, 25.4688, 54.5 ),
                },
                ['Expansion Area23'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 232.5, 26.9609, 30.5 ),
                },
                ['Mass11'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 164.5, 20.4766, 233.5 ),
                },
                ['Mass5'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 40.5, 18.6914, 71.5 ),
                },
            },
        },
    },
    Chains = {
    },
    --[[                                                                           ]]--
    --[[  Orders                                                                   ]]--
    --[[                                                                           ]]--
    next_queue_id = '1',
    Orders = {
    },
    --[[                                                                           ]]--
    --[[  Platoons                                                                 ]]--
    --[[                                                                           ]]--
    next_platoon_id = '1',
    Platoons = 
    {
    },
    --[[                                                                           ]]--
    --[[  Armies                                                                   ]]--
    --[[                                                                           ]]--
    next_army_id = '3',
    next_group_id = '1',
    next_unit_id = '7',
    Armies = 
    {
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_1'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_2'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
    },
}
