--[[                                                                           ]]--
--[[  Automatically generated code (do not edit)                               ]]--
--[[                                                                           ]]--
--[[                                                                           ]]--
--[[  Scenario                                                                 ]]--
--[[                                                                           ]]--
Scenario = {
    next_area_id = '3',
    --[[                                                                           ]]--
    --[[  Props                                                                    ]]--
    --[[                                                                           ]]--
    Props = {
    },
    --[[                                                                           ]]--
    --[[  Areas                                                                    ]]--
    --[[                                                                           ]]--
    Areas = {
        ['AREA_1'] = {
            ['rectangle'] = RECTANGLE( 5, 5, 251, 251 ),
        },
    },
    --[[                                                                           ]]--
    --[[  Markers                                                                  ]]--
    --[[                                                                           ]]--
    MasterChain = {
        ['_MASTERCHAIN_'] = {
            Markers = {
                ['AirPN01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN02 AirPN00 AirPN03 AirPN04 AirPN05 AirPN06 AirPN07 AirPN08' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 127.5, 52.9922, 127.5 ),
                },
                ['Hydrocarbon4'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 44.5, 61.7207, 156.5 ),
                },
                ['Expansion Area 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 60.5404, 62.7246, 146.21 ),
                },
                ['Expansion Area13'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 151.5, 53.9531, 104.5 ),
                },
                ['LandPN00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN02 LandPN03 L LandPN12' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 24.5, 61.9766, 130.5 ),
                },
                ['Mass 2'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 38.5, 62.0645, 112.5 ),
                },
                ['Combat Zone 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 71.5, 57.9453, 111.5 ),
                },
                ['LandPN07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN08 LandPN13 LandPN10' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 184.5, 57.9844, 171.5 ),
                },
                ['Defensive Point6'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 64.3296, 61.6891, 127.984 ),
                },
                ['Defensive Point16'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 162.944, 55.0278, 116.562 ),
                },
                ['Mass 14'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 159.5, 53.9961, 93.5 ),
                },
                ['Mass 8'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 217.5, 62.1777, 143.5 ),
                },
                ['Rally Point 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 63.2749, 58.8823, 113.991 ),
                },
                ['Hydrocarbon7'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 211.5, 61.709, 99.5 ),
                },
                ['LandPN05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN03 LandPN02 LandPN06 ' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 107.5, 53.3848, 137.5 ),
                },
                ['LandPN03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN02 LandPN04 LandPN05 LandPN00 LandPN09 ' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 71.5, 57.9453, 111.5 ),
                },
                ['AirPN07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN06 AirPN03 AirPN01' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 127.5, 53.002, 84.5 ),
                },
                ['Protected Experimental Construction 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 42.2606, 61.7728, 151.604 ),
                },
                ['ARMY_1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 1.2256e-006, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 231.5, 61.9824, 125.5 ),
                },
                ['Mass 13'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 95.5, 53.9961, 162.5 ),
                },
                ['Mass 7'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 215.5, 61.3281, 119.5 ),
                },
                ['Mass 6'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 232.5, 61.8242, 136.5 ),
                },
                ['LandPN08'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN06 LandPN07 LandPN01 LandPN13 LandPN10' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 184.5, 58.0273, 144.5 ),
                },
                ['AirPN00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN01 AirPN03 AirPN05' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 24.5, 61.9766, 130.5 ),
                },
                ['Rally Point 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 191.353, 58.8176, 141.394 ),
                },
                ['AirPN08'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN04 AirPN05 AirPN01' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 127.5, 53.002, 171.5 ),
                },
                ['Expansion Area8'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 149.5, 58.7773, 150.5 ),
                },
                ['LandPN04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN03 LandPN02 LandPN09' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 71.5, 57.9844, 84.5 ),
                },
                ['Defensive Point17'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 91.3271, 55.1912, 136.233 ),
                },
                ['Mass 12'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 180.5, 62.3633, 99.5 ),
                },
                ['Expansion Area14'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 103.5, 53.959, 152.5 ),
                },
                ['ARMY_2'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 2.44903e-007, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 24.5, 61.9766, 130.5 ),
                },
                ['AirPN06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN01 AirPN04 AirPN02 AirPN07' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 184.5, 64.7715, 84.5 ),
                },
                ['Mass 11'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 74.5, 62.3477, 155.5 ),
                },
                ['AirPN05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN01 AirPN03 AirPN00 AirPN08' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 71.5, 64.5898, 171.5 ),
                },
                ['Mass 4'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 24.5, 61.9922, 142.5 ),
                },
                ['LandPN06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN05 LandPN08 LandPN13' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 148.5, 53.6387, 113.5 ),
                },
                ['AirPN03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN00 AirPN01 AirPN05 AirPN07' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 71.5, 57.9844, 84.5 ),
                },
                ['Transport Marker 01'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 184.5, 57.9844, 171.5 ),
                },
                ['Defensive Point 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 79.0936, 61.8335, 149 ),
                },
                ['Expansion Area 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 195.459, 62.8589, 107.108 ),
                },
                ['LandPN01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN08 LandPN13 LandPN11' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 231.5, 61.9824, 125.5 ),
                },
                ['AirPN04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN02 AirPN01 AirPN06 AirPN08' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 184.5, 57.9844, 171.5 ),
                },
                ['LandPN02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN00 LandPN03 LandPN04 LandPN05' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 38.5, 62.0645, 112.5 ),
                },
                ['LandPN09'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN04 LandPN03' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 112.5, 58.2227, 100.5 ),
                },
                ['Mass 16'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 143.5, 58.2676, 155.5 ),
                },
                ['Defensive Point 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 117.771, 57.8298, 113.579 ),
                },
                ['Mass 9'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 71.5, 57.9844, 84.5 ),
                },
                ['Mass 1'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 23.5, 61.8164, 119.5 ),
                },
                ['Combat Zone 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 184.5, 58.0273, 144.5 ),
                },
                ['Mass 3'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 41.5, 61.2676, 136.5 ),
                },
                ['AirPN02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN01 AirPN04 AirPN06' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 231.5, 61.9824, 125.5 ),
                },
                ['Mass 10'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 184.5, 57.9844, 171.5 ),
                },
                ['Defensive Point4'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 190.449, 61.9877, 124.961 ),
                },
                ['Combat Zone16'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 148.5, 53.6387, 113.5 ),
                },
                ['Defensive Point15'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 127.5, 52.9922, 127.5 ),
                },
                ['Defensive Point3'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 137.334, 57.6787, 141.432 ),
                },
                ['Protected Experimental Construction 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 214.142, 61.851, 103.306 ),
                },
                ['LandPN10'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN07 LandPN08' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 143.5, 58.2676, 155.5 ),
                },
                ['Mass 15'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 112.5, 58.2227, 100.5 ),
                },
                ['Combat Zone15'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 107.5, 53.3848, 137.5 ),
                },
                ['LandPN13'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN01 LandPN08 LandPN07 LandPN06' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 217.5, 62.1777, 143.5 ),
                },
                ['Mass 5'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 231.5, 61.9922, 113.5 ),
                },
                ['Defensive Point5'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 176.575, 61.958, 106.569 ),
                },
                ['Transport Marker 02'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 127.5, 52.9922, 127.5 ),
                },
                ['Expansion Area10'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000469446, 0 ),
                    ['position'] = VECTOR3( 100.5, 58.9648, 103.5 ),
                },
                ['Transport Marker 00'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000402927, 0 ),
                    ['position'] = VECTOR3( 71.5, 57.9844, 84.5 ),
                },
                ['LandPN11'] = {
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['adjacentTo'] = STRING( 'LandPN01' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 195.5, 62.8418, 107.5 ),
                },
                ['LandPN12'] = {
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['adjacentTo'] = STRING( 'LandPN00' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 60.5, 62.7793, 147.5 ),
                },
            },
        },
    },
    Chains = {
    },
    --[[                                                                           ]]--
    --[[  Orders                                                                   ]]--
    --[[                                                                           ]]--
    next_queue_id = '1',
    Orders = {
    },
    --[[                                                                           ]]--
    --[[  Platoons                                                                 ]]--
    --[[                                                                           ]]--
    next_platoon_id = '1',
    Platoons = 
    {
    },
    --[[                                                                           ]]--
    --[[  Armies                                                                   ]]--
    --[[                                                                           ]]--
    next_army_id = '3',
    next_group_id = '1',
    next_unit_id = '4',
    Armies = 
    {
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_1'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_2'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
    },
}
