--[[                                                                           ]]--
--[[  Automatically generated code (do not edit)                               ]]--
--[[                                                                           ]]--
--[[                                                                           ]]--
--[[  Scenario                                                                 ]]--
--[[                                                                           ]]--
Scenario = {
    next_area_id = '4',
    --[[                                                                           ]]--
    --[[  Props                                                                    ]]--
    --[[                                                                           ]]--
    Props = {
    },
    --[[                                                                           ]]--
    --[[  Areas                                                                    ]]--
    --[[                                                                           ]]--
    Areas = {
        ['AREA_1'] = {
            ['rectangle'] = RECTANGLE( 5, 5, 507, 507 ),
        },
    },
    --[[                                                                           ]]--
    --[[  Markers                                                                  ]]--
    --[[                                                                           ]]--
    MasterChain = {
        ['_MASTERCHAIN_'] = {
            Markers = {
                ['Transport Marker 07'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 255.5, 40.4629, 348.5 ),
                },
                ['AirPN01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN04 AirPN00 AirPN16 AirPN13 AirPN02 AirPN09' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 61.5, 27.3809, 325.5 ),
                },
                ['Mass14'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 425.5, 30.248, 352.5 ),
                },
                ['Mass36'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 315.5, 34.9805, 228.5 ),
                },
                ['Transport Marker 04'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 139.5, 31.1719, 256.5 ),
                },
                ['Defensive Point 8'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 280.172, 39.9954, 161.85 ),
                },
                ['Mass 03'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 339.5, 38.1211, 130.5 ),
                },
                ['Combat Zone 20'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 322.5, 34.3262, 250.5 ),
                },
                ['Mass25'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 446.5, 28.0176, 169.5 ),
                },
                ['Mass35'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 194.5, 34.918, 228.5 ),
                },
                ['Mass3'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 64.5, 27.7363, 177.5 ),
                },
                ['AirPN15'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN13 AirPN00 AirPN11 AirPN03 AirPN10 AirPN02' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 165.5, 37.5332, 133.5 ),
                },
                ['LandPN11'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN04 LandPN12 LandPN20 LandPN06' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 255.5, 40.502, 163.5 ),
                },
                ['Large Expansion Area 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ffff0080' ),
                    ['type'] = STRING( 'Large Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000134945, 0 ),
                    ['position'] = VECTOR3( 356.5, 32.1211, 253.5 ),
                },
                ['Defensive Point 11'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 283.194, 39.6216, 346.488 ),
                },
                ['LandPN19'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN18 LandPN12 LandPN00' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( -3.14159, 0.0037725, 0 ),
                    ['position'] = VECTOR3( 120.5, 40.0605, 45.5 ),
                },
                ['Mass11'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 457.5, 27.0117, 332.5 ),
                },
                ['AirPN12'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN08 AirPN04 AirPN16 AirPN17 AirPN09' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 255.5, 47.0977, 461.5 ),
                },
                ['Rally Point 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 94.5, 29.2422, 209.5 ),
                },
                ['AirPN10'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN15 AirPN18 AirPN13 AirPN02 AirPN14 AirPN11 AirPN06 AirPN00' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 255.5, 40.502, 163.5 ),
                },
                ['AirPN07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN11 AirPN06 AirPN18' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 461.5, 37.6055, 50.5 ),
                },
                ['Protected Experimental Construction 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 452.208, 29.2925, 366.123 ),
                },
                ['LandPN20'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN11 LandPN06 LandPN18 LandPN17 LandPN21' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 319.5, 39.7012, 130.5 ),
                },
                ['Mass4'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 57.5, 27.2148, 184.5 ),
                },
                ['Transport Marker 03'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 50.5, 37.6719, 461.5 ),
                },
                ['AirPN09'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN16 AirPN17 AirPN13 AirPN02 AirPN14 AirPN12 AirPN05 AirPN01' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 255.5, 40.4629, 348.5 ),
                },
                ['Rally Point 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 417.5, 29.0684, 216.5 ),
                },
                ['LandPN13'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN05 LandPN10 LandPN14 LandPN15 LandPN12' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 192.5, 39.7188, 381.5 ),
                },
                ['Transport Marker 06'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 255.5, 40.502, 163.5 ),
                },
                ['Mass21'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 89.5, 30.8535, 356.5 ),
                },
                ['AirPN16'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN13 AirPN01 AirPN04 AirPN12 AirPN09 AirPN02' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 165.5, 37.5273, 378.5 ),
                },
                ['LandPN04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN00 LandPN08 LandPN05 LandPN12 LandPN11' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 139.5, 31.166, 239.5 ),
                },
                ['Mass17'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 62.5, 27.3867, 314.5 ),
                },
                ['Mass31'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 435.5, 27.5781, 237.5 ),
                },
                ['Mass13'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 487.5, 25.2461, 336.5 ),
                },
                ['Mass18'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 55.5, 27.0488, 319.5 ),
                },
                ['Mass 01'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 172.5, 38.2109, 130.5 ),
                },
                ['AirPN06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN07 AirPN05 AirPN14 AirPN18 AirPN02 AirPN10' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 458.5, 27.0684, 174.5 ),
                },
                ['Mass33'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 179.5, 37.875, 144.5 ),
                },
                ['Mass8'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0.10472, 0.0017035, 0 ),
                    ['position'] = VECTOR3( 76.5, 27.5801, 237.5 ),
                },
                ['Transport Marker 02'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 461.5, 37.459, 461.5 ),
                },
                ['Hydrocarbon38'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 432.5, 28.0703, 296.5 ),
                },
                ['LandPN01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN05 LandPN08 LandPN14' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 61.5, 27.3809, 325.5 ),
                },
                ['LandPN02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN17 LandPN09 LandPN06' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 458.5, 27.0684, 174.5 ),
                },
                ['LandPN09'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN06 LandPN07 LandPN02 LandPN03' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 415.5, 28.6211, 256.5 ),
                },
                ['Mass1'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 50.5, 27.2852, 168.5 ),
                },
                ['Mass34'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 333.5, 37.7871, 143.5 ),
                },
                ['Mass 02'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 339.5, 38.127, 381.5 ),
                },
                ['Defensive Point 6'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 235.678, 39.9034, 345.478 ),
                },
                ['Combat Zone 18'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 319.182, 39.4084, 380.005 ),
                },
                ['Defensive Point 9'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 351.5, 33.002, 215.5 ),
                },
                ['Mass 00'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 172.5, 38.2227, 381.5 ),
                },
                ['Mass15'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 436.5, 27.5801, 280.5 ),
                },
                ['Combat Zone 14'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 93.5, 28.4883, 256.5 ),
                },
                ['Combat Zone 13'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 415.5, 28.627, 254.5 ),
                },
                ['Mass10'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 443.5, 27.8457, 323.5 ),
                },
                ['LandPN00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN08 LandPN04 LandPN19' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 58.5, 27.4844, 172.5 ),
                },
                ['Rally Point 04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000134945, 0 ),
                    ['position'] = VECTOR3( 175.014, 33.4258, 259.355 ),
                },
                ['AirPN04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN12 AirPN01 AirPN16' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 50.5, 37.6719, 461.5 ),
                },
                ['LandPN07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN06 LandPN10 LandPN21 LandPN09 LandPN03' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 369.5, 31.2988, 273.5 ),
                },
                ['LandPN17'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN18 LandPN20 LandPN02' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( -3.14159, 0.0037725, 0 ),
                    ['position'] = VECTOR3( 389.5, 40.209, 45.5 ),
                },
                ['ARMY_3'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 61.5, 27.3809, 325.5 ),
                },
                ['Mass27'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 464.5, 26.7246, 180.5 ),
                },
                ['Expansion Area 22'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 337.5, 37.7324, 374.5 ),
                },
                ['Mass2'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 60.5, 28.1211, 162.5 ),
                },
                ['Mass24'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 102.5, 29.6191, 297.5 ),
                },
                ['AirPN18'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN11 AirPN07 AirPN14 AirPN06 AirPN10 AirPN02' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 345.5, 37.5273, 133.5 ),
                },
                ['Defensive Point 5'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 155.5, 32.498, 282.5 ),
                },
                ['LandPN05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN01 LandPN08 LandPN04 LandPN13 LandPN10' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 139.5, 31.2012, 273.5 ),
                },
                ['LandPN03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN16 LandPN09 LandPN07' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 449.5, 27.4238, 328.5 ),
                },
                ['Expansion Area 23'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 176.5, 38.0684, 137.5 ),
                },
                ['ARMY_1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 58.5, 27.4844, 172.5 ),
                },
                ['Mass38'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 315.5, 34.9961, 287.5 ),
                },
                ['Combat Zone 19'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 320.509, 39.2466, 136.297 ),
                },
                ['LandPN21'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN10 LandPN16 LandPN15 LandPN07 LandPN20' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 319.5, 39.6133, 381.5 ),
                },
                ['Mass32'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 407.5, 29.6758, 213.5 ),
                },
                ['Mass9'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 450.5, 27.291, 316.5 ),
                },
                ['Expansion Area 24'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 179.5, 38.4551, 375.5 ),
                },
                ['Defensive Point 1'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 93.5, 28.7656, 237.5 ),
                },
                ['AirPN00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN01 AirPN03 AirPN15 AirPN13 AirPN02 AirPN10' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 58.5, 27.4844, 172.5 ),
                },
                ['AirPN14'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN02 AirPN06 AirPN05 AirPN17 AirPN18 AirPN09 AirPN10' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 369.5, 31.2813, 256.5 ),
                },
                ['Rally Point 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 92.5, 28.9766, 294.5 ),
                },
                ['AirPN08'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN12 AirPN05 AirPN17' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 461.5, 37.459, 461.5 ),
                },
                ['Mass39'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0.00872665, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 183.5, 38.4609, 370.5 ),
                },
                ['Mass37'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 194.5, 34.9414, 286.5 ),
                },
                ['Mass19'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 73.5, 28.5254, 330.5 ),
                },
                ['LandPN06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN07 LandPN11 LandPN20 LandPN09 LandPN02' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 369.5, 31.2988, 239.5 ),
                },
                ['LandPN08'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN01 LandPN00 LandPN05 LandPN04' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 93.5, 28.4883, 256.5 ),
                },
                ['Mass20'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 61.5, 27.582, 336.5 ),
                },
                ['Hydrocarbon37'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 81.5, 28.3613, 213.5 ),
                },
                ['ARMY_2'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 449.5, 27.4238, 328.5 ),
                },
                ['Combat Zone 17'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 191.003, 39.3921, 378.3 ),
                },
                ['LandPN10'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN13 LandPN05 LandPN07 LandPN21' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 255.5, 40.4629, 348.5 ),
                },
                ['Mass40'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 333.5, 37.6641, 367.5 ),
                },
                ['LandPN12'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN04 LandPN11 LandPN18 LandPN19 LandPN13' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 192.5, 39.6465, 130.5 ),
                },
                ['LandPN15'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN16 LandPN14 LandPN13 LandPN21' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 255.5, 46.5801, 455.5 ),
                },
                ['Mass22'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 17.5, 25.7012, 348.5 ),
                },
                ['AirPN03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN11 AirPN00 AirPN15' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 50.5, 37.5137, 50.5 ),
                },
                ['AirPN02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN13 AirPN14 AirPN09 AirPN10 AirPN00 AirPN01 AirPN06 AirPN05 AirPN16 AirPN15 AirPN18 AirPN17' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 255.5, 48.8535, 255.5 ),
                },
                ['LandPN14'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN15 LandPN01 LandPN13' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 120.5, 40.1465, 466.5 ),
                },
                ['AirPN05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN08 AirPN06 AirPN14 AirPN17 AirPN02 AirPN09' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 449.5, 27.4238, 328.5 ),
                },
                ['Protected Experimental Construction 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 58.1245, 30.2299, 129.304 ),
                },
                ['Defensive Point 2'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 94.5, 28.8535, 277.5 ),
                },
                ['LandPN16'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN15 LandPN21 LandPN03' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 389.5, 40.1211, 466.5 ),
                },
                ['AirPN11'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN07 AirPN03 AirPN15 AirPN18 AirPN10 ' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 256.5, 47.1133, 50.5 ),
                },
                ['Mass30'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 493.5, 26.2383, 157.5 ),
                },
                ['Protected Experimental Construction 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 65.9109, 29.5888, 361.768 ),
                },
                ['Mass7'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 102.5, 29.6191, 213.5 ),
                },
                ['Transport Marker 01'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 461.5, 37.6055, 50.5 ),
                },
                ['Expansion Area 21'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 336.5, 37.8945, 137.5 ),
                },
                ['AirPN13'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN15 AirPN00 AirPN16 AirPN01 AirPN02 AirPN09 AirPN10' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 139.5, 31.1719, 256.5 ),
                },
                ['Rally Point 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 419.5, 29.0352, 297.5 ),
                },
                ['AirPN17'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN12 AirPN08 AirPN14 AirPN05 AirPN09 AirPN02' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 345.5, 37.5332, 378.5 ),
                },
                ['Mass12'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 447.5, 27.7441, 338.5 ),
                },
                ['Transport Marker 00'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 50.5, 37.5137, 50.5 ),
                },
                ['LandPN18'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LandPN19 LandPN17 LandPN20 LandPN12' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( -3.14159, 0.0037725, 0 ),
                    ['position'] = VECTOR3( 256.5, 46.6016, 56.5 ),
                },
                ['Transport Marker 05'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 369.5, 31.2813, 256.5 ),
                },
                ['Mass16'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 407.5, 29.6758, 299.5 ),
                },
                ['Hydrocarbon40'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 432.5, 28.0586, 217.5 ),
                },
                ['Mass5'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 88.5, 31.7852, 140.5 ),
                },
                ['Mass26'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 458.5, 27.6797, 163.5 ),
                },
                ['Defensive Point 12'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 354.5, 32.7207, 287.5 ),
                },
                ['Hydrocarbon39'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 81.5, 28.25, 294.5 ),
                },
                ['Defensive Point 10'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 415.5, 29.0449, 282.5 ),
                },
                ['Mass23'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 76.5, 27.6973, 277.5 ),
                },
                ['Rally Point 05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000134945, 0 ),
                    ['position'] = VECTOR3( 329.761, 33.8549, 252.967 ),
                },
                ['Defensive Point 3'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 236.469, 40.0675, 162.911 ),
                },
                ['Protected Experimental Construction 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 448.771, 31.0206, 123.718 ),
                },
                ['Defensive Point 7'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 417.5, 28.7656, 238.5 ),
                },
                ['Defensive Point 4'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 155.5, 32.25, 234.5 ),
                },
                ['Large Expansion Area 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ffff0080' ),
                    ['type'] = STRING( 'Large Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000134945, 0 ),
                    ['position'] = VECTOR3( 150.5, 31.875, 257.5 ),
                },
                ['Mass6'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 25.5, 27.1055, 150.5 ),
                },
                ['Combat Zone 16'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 195.332, 39.5241, 132.293 ),
                },
                ['Combat Zone 15'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 188.5, 34.2617, 254.5 ),
                },
                ['Mass29'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 425.5, 31.625, 139.5 ),
                },
                ['ARMY_4'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 458.5, 27.0684, 174.5 ),
                },
                ['Mass28'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000930905, 0 ),
                    ['position'] = VECTOR3( 457.5, 27.0059, 185.5 ),
                },
            },
        },
    },
    Chains = {
    },
    --[[                                                                           ]]--
    --[[  Orders                                                                   ]]--
    --[[                                                                           ]]--
    next_queue_id = '1',
    Orders = {
    },
    --[[                                                                           ]]--
    --[[  Platoons                                                                 ]]--
    --[[                                                                           ]]--
    next_platoon_id = '1',
    Platoons = 
    {
    },
    --[[                                                                           ]]--
    --[[  Armies                                                                   ]]--
    --[[                                                                           ]]--
    next_army_id = '9',
    next_group_id = '6',
    next_unit_id = '302',
    Armies = 
    {
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_3'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_1'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_4'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                    ['GROUP_1'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                    ['GROUP_2'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['NEUTRAL_CIVILIAN'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                    ['WRECKAGE'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['UNIT_292'] = {
                                type = 'uel0202',
                                orders = '',
                                platoon = '',
                                Position = { 275.500000, 39.728516, 169.500000 },
                                Orientation = { 0.000000, -2.138029, 0.000000 },
                            },
                            ['UNIT_291'] = {
                                type = 'xal0203',
                                orders = '',
                                platoon = '',
                                Position = { 240.500000, 40.328125, 163.500000 },
                                Orientation = { 0.000000, -4.310965, 0.000000 },
                            },
                            ['UNIT_177'] = {
                                type = 'ual0303',
                                orders = '',
                                platoon = '',
                                Position = { 257.500000, 40.748047, 351.500000 },
                                Orientation = { 0.000000, -7.958699, 0.000000 },
                            },
                            ['UNIT_301'] = {
                                type = 'xal0203',
                                orders = '',
                                platoon = '',
                                Position = { 235.500000, 39.728516, 168.500000 },
                                Orientation = { 0.000000, -4.459317, 0.000000 },
                            },
                            ['UNIT_286'] = {
                                type = 'xal0203',
                                orders = '',
                                platoon = '',
                                Position = { 242.500000, 40.246094, 165.500000 },
                                Orientation = { 0.000000, -4.825836, 0.000000 },
                            },
                            ['UNIT_179'] = {
                                type = 'uel0303',
                                orders = '',
                                platoon = '',
                                Position = { 249.500000, 40.271484, 346.500000 },
                                Orientation = { 0.000000, -4.817108, 0.000000 },
                            },
                            ['UNIT_171'] = {
                                type = 'xal0203',
                                orders = '',
                                platoon = '',
                                Position = { 268.500000, 40.468750, 349.500000 },
                                Orientation = { 0.000000, -7.949973, 0.000000 },
                            },
                            ['UNIT_176'] = {
                                type = 'xal0203',
                                orders = '',
                                platoon = '',
                                Position = { 268.500000, 39.513672, 341.500000 },
                                Orientation = { 0.000000, -8.072147, 0.000000 },
                            },
                            ['UNIT_188'] = {
                                type = 'xal0203',
                                orders = '',
                                platoon = '',
                                Position = { 306.500000, 37.857422, 348.500000 },
                                Orientation = { 0.000000, -7.435102, 0.000000 },
                            },
                            ['UNIT_201'] = {
                                type = 'uel0202',
                                orders = '',
                                platoon = '',
                                Position = { 217.500000, 39.427734, 353.500000 },
                                Orientation = { 0.000000, -5.262167, 0.000000 },
                            },
                            ['UNIT_181'] = {
                                type = 'xal0203',
                                orders = '',
                                platoon = '',
                                Position = { 277.500000, 40.382813, 356.500000 },
                                Orientation = { 0.000000, -8.107055, 0.000000 },
                            },
                            ['UNIT_190'] = {
                                type = 'xal0203',
                                orders = '',
                                platoon = '',
                                Position = { 270.500000, 40.488281, 351.500000 },
                                Orientation = { 0.000000, -7.435102, 0.000000 },
                            },
                            ['UNIT_165'] = {
                                type = 'uel0202',
                                orders = '',
                                platoon = '',
                                Position = { 235.500000, 39.876953, 345.500000 },
                                Orientation = { 0.000000, -5.262167, 0.000000 },
                            },
                            ['UNIT_167'] = {
                                type = 'xal0203',
                                orders = '',
                                platoon = '',
                                Position = { 282.500000, 39.027344, 337.500000 },
                                Orientation = { 0.000000, -7.949973, 0.000000 },
                            },
                            ['UNIT_295'] = {
                                type = 'uel0202',
                                orders = '',
                                platoon = '',
                                Position = { 263.500000, 40.853516, 160.500000 },
                                Orientation = { 0.000000, -1.474802, 0.000000 },
                            },
                            ['UNIT_160'] = {
                                type = 'uel0202',
                                orders = '',
                                platoon = '',
                                Position = { 245.500000, 38.853516, 338.500000 },
                                Orientation = { 0.000000, -5.340707, 0.000000 },
                            },
                            ['UNIT_172'] = {
                                type = 'ual0303',
                                orders = '',
                                platoon = '',
                                Position = { 261.500000, 39.154297, 341.500000 },
                                Orientation = { 0.000000, -7.984879, 0.000000 },
                            },
                            ['UNIT_288'] = {
                                type = 'xal0203',
                                orders = '',
                                platoon = '',
                                Position = { 204.500000, 37.791016, 165.500000 },
                                Orientation = { 0.000000, -4.310965, 0.000000 },
                            },
                            ['UNIT_290'] = {
                                type = 'xal0203',
                                orders = '',
                                platoon = '',
                                Position = { 233.500000, 40.281250, 158.500000 },
                                Orientation = { 0.000000, -4.982917, 0.000000 },
                            },
                            ['UNIT_289'] = {
                                type = 'uel0202',
                                orders = '',
                                platoon = '',
                                Position = { 293.500000, 39.158203, 162.500000 },
                                Orientation = { 0.000000, -2.138029, 0.000000 },
                            },
                            ['UNIT_184'] = {
                                type = 'xal0203',
                                orders = '',
                                platoon = '',
                                Position = { 273.500000, 40.550781, 362.500000 },
                                Orientation = { 0.000000, -8.665563, 0.000000 },
                            },
                            ['UNIT_174'] = {
                                type = 'xal0203',
                                orders = '',
                                platoon = '',
                                Position = { 275.500000, 39.876953, 346.500000 },
                                Orientation = { 0.000000, -7.583454, 0.000000 },
                            },
                            ['UNIT_193'] = {
                                type = 'uel0202',
                                orders = '',
                                platoon = '',
                                Position = { 235.500000, 40.539063, 361.500000 },
                                Orientation = { 0.000000, -5.262167, 0.000000 },
                            },
                            ['UNIT_287'] = {
                                type = 'xal0203',
                                orders = '',
                                platoon = '',
                                Position = { 242.500000, 39.109375, 173.500000 },
                                Orientation = { 0.000000, -4.948009, 0.000000 },
                            },
                            ['UNIT_284'] = {
                                type = 'ual0303',
                                orders = '',
                                platoon = '',
                                Position = { 253.500000, 40.462891, 163.500000 },
                                Orientation = { 0.000000, -4.834562, 0.000000 },
                            },
                            ['UNIT_285'] = {
                                type = 'uel0303',
                                orders = '',
                                platoon = '',
                                Position = { 261.500000, 39.794922, 168.500000 },
                                Orientation = { 0.000000, -1.692970, 0.000000 },
                            },
                            ['UNIT_191'] = {
                                type = 'xal0203',
                                orders = '',
                                platoon = '',
                                Position = { 288.500000, 39.603516, 354.500000 },
                                Orientation = { 0.000000, -7.435102, 0.000000 },
                            },
                            ['UNIT_298'] = {
                                type = 'xal0203',
                                orders = '',
                                platoon = '',
                                Position = { 222.500000, 39.414063, 160.500000 },
                                Orientation = { 0.000000, -4.310965, 0.000000 },
                            },
                            ['UNIT_180'] = {
                                type = 'uel0202',
                                orders = '',
                                platoon = '',
                                Position = { 247.500000, 41.064453, 354.500000 },
                                Orientation = { 0.000000, -4.598941, 0.000000 },
                            },
                            ['UNIT_297'] = {
                                type = 'xal0203',
                                orders = '',
                                platoon = '',
                                Position = { 228.500000, 38.783203, 177.500000 },
                                Orientation = { 0.000000, -4.825836, 0.000000 },
                            },
                            ['UNIT_294'] = {
                                type = 'ual0303',
                                orders = '',
                                platoon = '',
                                Position = { 249.500000, 38.791016, 173.500000 },
                                Orientation = { 0.000000, -4.860742, 0.000000 },
                            },
                            ['UNIT_189'] = {
                                type = 'xal0203',
                                orders = '',
                                platoon = '',
                                Position = { 286.500000, 39.488281, 351.500000 },
                                Orientation = { 0.000000, -7.435102, 0.000000 },
                            },
                            ['UNIT_296'] = {
                                type = 'uel0202',
                                orders = '',
                                platoon = '',
                                Position = { 275.500000, 40.535156, 153.500000 },
                                Orientation = { 0.000000, -2.138029, 0.000000 },
                            },
                            ['UNIT_300'] = {
                                type = 'xal0203',
                                orders = '',
                                platoon = '',
                                Position = { 237.500000, 40.611328, 152.500000 },
                                Orientation = { 0.000000, -5.541425, 0.000000 },
                            },
                            ['UNIT_299'] = {
                                type = 'xal0203',
                                orders = '',
                                platoon = '',
                                Position = { 224.500000, 39.544922, 163.500000 },
                                Orientation = { 0.000000, -4.310965, 0.000000 },
                            },
                            ['UNIT_293'] = {
                                type = 'uel0202',
                                orders = '',
                                platoon = '',
                                Position = { 265.500000, 38.933594, 176.500000 },
                                Orientation = { 0.000000, -2.216569, 0.000000 },
                            },
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_2'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
    },
}
