--[[                                                                           ]]--
--[[  Automatically generated code (do not edit)                               ]]--
--[[                                                                           ]]--
--[[                                                                           ]]--
--[[  Scenario                                                                 ]]--
--[[                                                                           ]]--
Scenario = {
    next_area_id = '1',
    --[[                                                                           ]]--
    --[[  Props                                                                    ]]--
    --[[                                                                           ]]--
    Props = {
    },
    --[[                                                                           ]]--
    --[[  Areas                                                                    ]]--
    --[[                                                                           ]]--
    Areas = {
        ['AREA_1'] = {
            ['rectangle'] = RECTANGLE( 5, 5, 251, 251 ),
        },
    },
    --[[                                                                           ]]--
    --[[  Markers                                                                  ]]--
    --[[                                                                           ]]--
    MasterChain = {
        ['_MASTERCHAIN_'] = {
            Markers = {
                ['AmphPN10'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AmphPN08 AmphPN01 AmphPN07 AmphPN02 AmphPN09' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 71.5, 17.5, 154.5 ),
                },
                ['AirPN01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN00 AirPN02 AirPN03 AirPN04 AirPN07 AirPN06' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 69.5, 17.8906, 89.5 ),
                },
                ['WaterPN04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultWater' ),
                    ['adjacentTo'] = STRING( 'WaterPN05 WaterPN03 WaterPN09 WaterPN01 WaterPN00' ),
                    ['color'] = STRING( 'ff0000ff' ),
                    ['type'] = STRING( 'Water Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 71.5, 17.5, 154.5 ),
                },
                ['Mass 00'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 82.5, 17.8848, 79.5 ),
                },
                ['Mass 07'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 66.5, 17.8906, 76.5 ),
                },
                ['AmphPN00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AmphPN01 AmphPN06 AmphPN04' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 69.5, 17.8906, 89.5 ),
                },
                ['Mass 05'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 66.5, 17.877, 74.5 ),
                },
                ['Naval Area 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 166.229, 17.5, 108.88 ),
                },
                ['Mass 08'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 67.5, 17.8613, 104.5 ),
                },
                ['Mass 23'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 202.5, 17.8906, 96.5 ),
                },
                ['LandPN00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( '' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 69.5, 17.8906, 89.5 ),
                },
                ['WaterPN07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultWater' ),
                    ['adjacentTo'] = STRING( 'WaterPN08 WaterPN06' ),
                    ['color'] = STRING( 'ff0000ff' ),
                    ['type'] = STRING( 'Water Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 214.5, 17.5, 75.5 ),
                },
                ['Mass 33'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 117.5, 17.8809, 204.5 ),
                },
                ['AmphPN11'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AmphPN08 AmphPN05 AmphPN07 AmphPN03 AmphPN09' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 178.5, 17.5, 158.5 ),
                },
                ['Mass 17'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 194.5, 17.873, 110.5 ),
                },
                ['Mass 19'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 194.5, 17.8906, 108.5 ),
                },
                ['Mass 14'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 176.5, 17.8906, 86.5 ),
                },
                ['AmphPN08'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AmphPN06 AmphPN11 AmphPN10' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 127.5, 17.5, 222.5 ),
                },
                ['Naval Area 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 92.4586, 17.5, 102.608 ),
                },
                ['Mass 25'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 109.5, 17.8906, 189.5 ),
                },
                ['Rally Point 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 76.7906, 17.8799, 93.577 ),
                },
                ['Island 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Island' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 69.7687, 17.8906, 89.4778 ),
                },
                ['Transport Marker 00'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 69.5, 17.8906, 89.5 ),
                },
                ['Mass 26'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 111.5, 17.8906, 187.5 ),
                },
                ['Protected Experimental Construction 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 199.074, 17.2383, 84.1 ),
                },
                ['ARMY_1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 125.5, 17.8906, 194.5 ),
                },
                ['Combat Zone 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 128.5, 17.5, 127.5 ),
                },
                ['Island 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Island' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 125.91, 17.8906, 193.995 ),
                },
                ['Mass 09'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 69.5, 17.8711, 104.5 ),
                },
                ['AirPN09'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN02 AirPN06 AirPN05' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 238.449, 12.7219, 57.4261 ),
                },
                ['Rally Point 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 128.655, 17.8689, 183.264 ),
                },
                ['Combat Zone 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 53.6195, 10.8145, 164.133 ),
                },
                ['AirPN07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN01 AirPN04 AirPN06' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 23.5, 17.5, 62.5 ),
                },
                ['AmphPN06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AmphPN07 AmphPN08 AmphPN04 AmphPN00' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 125.5, 17.8906, 194.5 ),
                },
                ['AirPN00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN01 AirPN02 AirPN03 AirPN04 AirPN05 AirPN06' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 128.5, 17.5, 127.5 ),
                },
                ['Combat Zone 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 197.598, 11.707, 172.795 ),
                },
                ['Rally Point 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 180.676, 17.8594, 97.8427 ),
                },
                ['Defensive Point 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 189.994, 17.7095, 76.2405 ),
                },
                ['AirPN03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN02 AirPN00 AirPN01 AirPN05 AirPN08 AirPN04' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 125.5, 17.8906, 194.5 ),
                },
                ['WaterPN06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultWater' ),
                    ['adjacentTo'] = STRING( 'WaterPN07 WaterPN05 WaterPN02 WaterPN03 WaterPN00' ),
                    ['color'] = STRING( 'ff0000ff' ),
                    ['type'] = STRING( 'Water Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 178.5, 17.5, 158.5 ),
                },
                ['Mass 35'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 117.5, 17.8906, 202.5 ),
                },
                ['WaterPN09'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultWater' ),
                    ['adjacentTo'] = STRING( 'WaterPN08 WaterPN04' ),
                    ['color'] = STRING( 'ff0000ff' ),
                    ['type'] = STRING( 'Water Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 41.5, 17.5, 73.5 ),
                },
                ['Mass 22'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 204.5, 17.877, 96.5 ),
                },
                ['ARMY_2'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 69.5, 17.8906, 89.5 ),
                },
                ['Mass 15'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 178.5, 17.8906, 86.5 ),
                },
                ['Mass 03'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 82.5, 17.8867, 77.5 ),
                },
                ['AmphPN07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AmphPN06 AmphPN03 AmphPN09 AmphPN02 AmphPN10 AmphPN11' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 125.5, 17.5, 166.5 ),
                },
                ['Mass 30'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 138.5, 17.8906, 186.5 ),
                },
                ['Defensive Point 04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 57.549, 17.8906, 95.231 ),
                },
                ['WaterPN08'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultWater' ),
                    ['adjacentTo'] = STRING( 'WaterPN09 WaterPN07 WaterPN02 WaterPN01 WaterPN00' ),
                    ['color'] = STRING( 'ff0000ff' ),
                    ['type'] = STRING( 'Water Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 127.5, 17.5, 61.5 ),
                },
                ['WaterPN02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultWater' ),
                    ['adjacentTo'] = STRING( 'WaterPN03 WaterPN00 WaterPN01 WaterPN08 WaterPN06' ),
                    ['color'] = STRING( 'ff0000ff' ),
                    ['type'] = STRING( 'Water Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 166.5, 17.5, 108.5 ),
                },
                ['Naval Area 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 125.312, 17.5, 166.224 ),
                },
                ['Mass 32'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 115.5, 17.8848, 204.5 ),
                },
                ['Mass 20'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 202.5, 17.8867, 94.5 ),
                },
                ['AirPN05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN08 AirPN03 AirPN02 AirPN09 AirPN00' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 178.5, 17.5, 158.5 ),
                },
                ['Mass 01'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 84.5, 17.8613, 77.5 ),
                },
                ['AirPN02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN00 AirPN01 AirPN03 AirPN06 AirPN09 AirPN05' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 190.5, 17.8906, 93.5 ),
                },
                ['Mass 13'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 178.5, 17.8906, 84.5 ),
                },
                ['WaterPN05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultWater' ),
                    ['adjacentTo'] = STRING( 'WaterPN06 WaterPN04' ),
                    ['color'] = STRING( 'ff0000ff' ),
                    ['type'] = STRING( 'Water Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 127.5, 17.5, 222.5 ),
                },
                ['Mass 04'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 64.5, 17.8848, 74.5 ),
                },
                ['Mass 28'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 136.5, 17.8887, 184.5 ),
                },
                ['Mass 31'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 138.5, 17.877, 184.5 ),
                },
                ['Island 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Island' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 191.308, 17.8906, 92.1654 ),
                },
                ['Mass 11'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 69.5, 17.8906, 102.5 ),
                },
                ['Protected Experimental Construction 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 127.701, 16.5898, 208.331 ),
                },
                ['Defensive Point 05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 138.468, 17.8614, 201.929 ),
                },
                ['AmphPN05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AmphPN04 AmphPN12 AmphPN11' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 214.5, 17.5, 75.5 ),
                },
                ['Mass 24'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 109.5, 17.8887, 187.5 ),
                },
                ['Mass 21'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 204.5, 17.8633, 94.5 ),
                },
                ['Combat Zone 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 126.805, 12.6055, 40.473 ),
                },
                ['WaterPN01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultWater' ),
                    ['adjacentTo'] = STRING( 'WaterPN03 WaterPN00 WaterPN02 WaterPN08 WaterPN04' ),
                    ['color'] = STRING( 'ff0000ff' ),
                    ['type'] = STRING( 'Water Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 92.5, 17.5, 102.5 ),
                },
                ['Transport Marker 01'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 125.5, 17.8906, 194.5 ),
                },
                ['Transport Marker 02'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 190.5, 17.8906, 93.5 ),
                },
                ['WaterPN03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultWater' ),
                    ['adjacentTo'] = STRING( 'WaterPN04 WaterPN02 WaterPN01 WaterPN00 WaterPN06' ),
                    ['color'] = STRING( 'ff0000ff' ),
                    ['type'] = STRING( 'Water Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 125.5, 17.5, 166.5 ),
                },
                ['LandPN01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( '' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 190.5, 17.8906, 93.5 ),
                },
                ['Mass 27'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 111.5, 17.8906, 189.5 ),
                },
                ['LandPN02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( '' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 125.5, 17.8906, 194.5 ),
                },
                ['AmphPN04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AmphPN03 AmphPN05 AmphPN06 AmphPN00' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 190.5, 17.8906, 93.5 ),
                },
                ['ARMY_3'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 190.5, 17.8906, 93.5 ),
                },
                ['Mass 16'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 192.5, 17.873, 110.5 ),
                },
                ['AmphPN02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AmphPN01 AmphPN03 AmphPN09 AmphPN07 AmphPN10 AmphPN12' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 92.5, 17.5, 102.5 ),
                },
                ['Mass 06'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 64.5, 17.8906, 76.5 ),
                },
                ['Defensive Point 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 83.0008, 17.8906, 75.2562 ),
                },
                ['Mass 02'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 84.5, 17.8438, 79.5 ),
                },
                ['AmphPN12'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AmphPN01 AmphPN05 AmphPN03 AmphPN02 AmphPN09' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 127.5, 17.5, 61.5 ),
                },
                ['Mass 10'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 67.5, 17.8906, 102.5 ),
                },
                ['AmphPN09'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AmphPN07 AmphPN02 AmphPN03 AmphPN10 AmphPN11 AmphPN12' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 128.5, 17.5, 127.5 ),
                },
                ['WaterPN00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultWater' ),
                    ['adjacentTo'] = STRING( 'WaterPN01 WaterPN02 WaterPN03 WaterPN04 WaterPN06 WaterPN08' ),
                    ['color'] = STRING( 'ff0000ff' ),
                    ['type'] = STRING( 'Water Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 128.5, 17.5, 127.5 ),
                },
                ['Mass 18'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 192.5, 17.8906, 108.5 ),
                },
                ['Mass 12'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 176.5, 17.8867, 84.5 ),
                },
                ['Protected Experimental Construction 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 55.4303, 16.5566, 80.8124 ),
                },
                ['AirPN06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN01 AirPN07 AirPN02 AirPN09 AirPN00' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 127.5, 17.5, 61.5 ),
                },
                ['AmphPN01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AmphPN00 AmphPN02 AmphPN10 AmphPN12' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 41.5, 17.5, 73.5 ),
                },
                ['AmphPN03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AmphPN02 AmphPN04 AmphPN07 AmphPN09 AmphPN11 AmphPN12' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 166.5, 17.5, 108.5 ),
                },
                ['AirPN04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN08 AirPN03 AirPN01 AirPN07 AirPN00' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 71.5, 17.5, 154.5 ),
                },
                ['Mass 29'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 136.5, 17.8906, 186.5 ),
                },
                ['Defensive Point 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 191.899, 17.8799, 110.287 ),
                },
                ['Mass 34'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 115.5, 17.8906, 202.5 ),
                },
                ['Defensive Point 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 108.04, 17.8478, 185.4 ),
                },
                ['AirPN08'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN05 AirPN03 AirPN04' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.00033617, 0 ),
                    ['position'] = VECTOR3( 126.5, 17.5, 241.5 ),
                },
                ['Naval Rally Point 00'] = {
                    ['color'] = STRING( 'ff00FFFF' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Naval Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 126.5, 17.5, 149.5 ),
                },
                ['Naval Rally Point 01'] = {
                    ['color'] = STRING( 'ff00FFFF' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Naval Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 153.5, 17.5, 114.5 ),
                },
                ['Naval Rally Point 02'] = {
                    ['color'] = STRING( 'ff00FFFF' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Naval Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 103.5, 17.5, 110.5 ),
                },
                ['Naval Defensive Point 00'] = {
                    ['color'] = STRING( 'ff0080FF' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Naval Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 143.5, 17.5, 156.5 ),
                },
                ['Naval Defensive Point 01'] = {
                    ['color'] = STRING( 'ff0080FF' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Naval Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 105.5, 17.5, 156.5 ),
                },
                ['Naval Defensive Point 02'] = {
                    ['color'] = STRING( 'ff0080FF' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Naval Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 146.5, 17.5, 100.5 ),
                },
                ['Naval Defensive Point 03'] = {
                    ['color'] = STRING( 'ff0080FF' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Naval Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 164.5, 17.5, 125.5 ),
                },
                ['Naval Defensive Point 04'] = {
                    ['color'] = STRING( 'ff0080FF' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Naval Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 113.5, 17.5, 99.5 ),
                },
                ['Naval Defensive Point 05'] = {
                    ['color'] = STRING( 'ff0080FF' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Naval Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 95.5, 17.5, 118.5 ),
                },
            },
        },
    },
    Chains = {
    },
    --[[                                                                           ]]--
    --[[  Orders                                                                   ]]--
    --[[                                                                           ]]--
    next_queue_id = '1',
    Orders = {
    },
    --[[                                                                           ]]--
    --[[  Platoons                                                                 ]]--
    --[[                                                                           ]]--
    next_platoon_id = '1',
    Platoons = 
    {
    },
    --[[                                                                           ]]--
    --[[  Armies                                                                   ]]--
    --[[                                                                           ]]--
    next_army_id = '5',
    next_group_id = '1',
    next_unit_id = '2',
    Armies = 
    {
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_3'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_1'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_2'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
    },
}
