--[[                                                                           ]]--
--[[  Automatically generated code (do not edit)                               ]]--
--[[                                                                           ]]--
--[[                                                                           ]]--
--[[  Scenario                                                                 ]]--
--[[                                                                           ]]--
Scenario = {
    next_area_id = '1',
    --[[                                                                           ]]--
    --[[  Props                                                                    ]]--
    --[[                                                                           ]]--
    Props = {
    },
    --[[                                                                           ]]--
    --[[  Areas                                                                    ]]--
    --[[                                                                           ]]--
    Areas = {
        ['AREA_1'] = {
            ['rectangle'] = RECTANGLE( 5, 5, 507, 507 ),
        },
    },
    --[[                                                                           ]]--
    --[[  Markers                                                                  ]]--
    --[[                                                                           ]]--
    MasterChain = {
        ['_MASTERCHAIN_'] = {
            Markers = {
                ['Transport Marker 07'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 92.0185, 18.7153, 105.108 ),
                },
                ['AirPN01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN00 AirPN07 AirPN08 AirPN05' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 372.42, 20.4437, 137.407 ),
                },
                ['Mass14'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.0174533, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 374.5, 20.6504, 154.5 ),
                },
                ['Naval Link 01'] = {
                    ['color'] = STRING( 'ffff0000' ),
                    ['type'] = STRING( 'Naval Link' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 275.006, 16.3634, 234.791 ),
                },
                ['Naval Link 05'] = {
                    ['color'] = STRING( 'ffff0000' ),
                    ['type'] = STRING( 'Naval Link' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 319.001, 15.3028, 314.484 ),
                },
                ['Naval Area 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 370.5, 17.5, 75.5 ),
                },
                ['Mass3'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.0174533, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 147.5, 20.6992, 340.5 ),
                },
                ['Naval Link 04'] = {
                    ['color'] = STRING( 'ffff0000' ),
                    ['type'] = STRING( 'Naval Link' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 102.559, 14.3984, 406.252 ),
                },
                ['Naval Area 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 115.5, 17.5, 116.5 ),
                },
                ['Expansion Area 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 241.5, 20.9688, 179.5 ),
                },
                ['Mass11'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.0174533, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 346.5, 20.668, 152.5 ),
                },
                ['AMPN06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AMPN05 AMPN07 AMPN15 AMPN17 AMPN18' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 251.227, 11.8987, 31.6529 ),
                },
                ['LPN04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LPN02 LPN03 LPN05' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 354.932, 20.8125, 246.219 ),
                },
                ['AMPN09'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AMPN01 AMPN02 AMPN10 AMPN20 AMPN08' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 141.128, 20.6562, 360.004 ),
                },
                ['Combat Zone 10'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 244.5, 20.8809, 176.5 ),
                },
                ['Protected Experimental Construction 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 390.5, 18.2617, 124.5 ),
                },
                ['Combat Zone 12'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 341.5, 20.707, 263.5 ),
                },
                ['Mass4'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.0174533, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 163.5, 20.6895, 357.5 ),
                },
                ['Transport Marker 03'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 93.4373, 18.14, 347.283 ),
                },
                ['AirPN09'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN08 AirPN03 AirPN04 AirPN00' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 38.5, 17.5, 249.5 ),
                },
                ['WPN11'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultWater' ),
                    ['adjacentTo'] = STRING( 'WPN08 WPN09 WPN10' ),
                    ['color'] = STRING( 'ff0000ff' ),
                    ['type'] = STRING( 'Water Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 473.561, 12.4473, 27.4218 ),
                },
                ['WPN04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultWater' ),
                    ['adjacentTo'] = STRING( 'WPN02 WPN08' ),
                    ['color'] = STRING( 'ff0000ff' ),
                    ['type'] = STRING( 'Water Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 483.5, 17.5, 483.5 ),
                },
                ['Transport Marker 06'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 417.052, 18.2709, 414.871 ),
                },
                ['Defensive Point 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 438.5, 18.1563, 401.5 ),
                },
                ['Naval Link 13'] = {
                    ['color'] = STRING( 'ffff0000' ),
                    ['type'] = STRING( 'Naval Link' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 209.939, 13.686, 119.924 ),
                },
                ['WPN00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultWater' ),
                    ['adjacentTo'] = STRING( 'WPN01 WPN02 WPN03' ),
                    ['color'] = STRING( 'ff0000ff' ),
                    ['type'] = STRING( 'Water Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 32.5, 17.5, 483.5 ),
                },
                ['AMPN03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AMPN02 AMPN12 AMPN04' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 484.906, 12.8903, 481.964 ),
                },
                ['Naval Link 06'] = {
                    ['color'] = STRING( 'ffff0000' ),
                    ['type'] = STRING( 'Naval Link' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 196.283, 15.8659, 197.692 ),
                },
                ['Expansion Area 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000202179, 0 ),
                    ['position'] = VECTOR3( 272.5, 20.6973, 333.5 ),
                },
                ['Mass13'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.0174533, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 364.5, 20.6035, 141.5 ),
                },
                ['Mass18'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.0174533, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 413.5, 18.166, 208.5 ),
                },
                ['Hydrocarbon25'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.0174533, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 367.5, 18.3066, 112.5 ),
                },
                ['AirPN06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN00 AirPN07 AirPN04 AirPN02' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 278.5, 17.5, 476.5 ),
                },
                ['Naval Link 08'] = {
                    ['color'] = STRING( 'ffff0000' ),
                    ['type'] = STRING( 'Naval Link' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 440.712, 13.6574, 195.692 ),
                },
                ['Mass8'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.0174533, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 234.5, 20.9336, 346.5 ),
                },
                ['Transport Marker 02'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 177.279, 19.8286, 395.667 ),
                },
                ['Defensive Point 05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 70.5, 17.9512, 112.5 ),
                },
                ['WPN05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultWater' ),
                    ['adjacentTo'] = STRING( 'WPN02 WPN08' ),
                    ['color'] = STRING( 'ff0000ff' ),
                    ['type'] = STRING( 'Water Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 366.5, 17.5, 369.5 ),
                },
                ['Expansion Area 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 336.5, 20.7656, 269.5 ),
                },
                ['Transport Marker 08'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 312.61, 24.4593, 196.517 ),
                },
                ['LPN05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LPN03 LPN04' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 374.077, 20.5673, 146.351 ),
                },
                ['Naval Link 11'] = {
                    ['color'] = STRING( 'ffff0000' ),
                    ['type'] = STRING( 'Naval Link' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 275.238, 15.5645, 81.7196 ),
                },
                ['AMPN05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AMPN04 AMPN15 AMPN06' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 483.715, 12.8327, 21.6748 ),
                },
                ['AMPN13'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AMPN10 AMPN11 AMPN14 AMPN19' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 300.02, 17.9453, 302.204 ),
                },
                ['LPN00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LPN01 LPN02' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 134.596, 20.5912, 361.463 ),
                },
                ['Mass15'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.0174533, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 322.5, 24.2383, 195.5 ),
                },
                ['Hydrocarbon26'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.0174533, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 143.5, 18.248, 402.5 ),
                },
                ['Combat Zone 13'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 167.5, 20.6641, 243.5 ),
                },
                ['WPN10'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultWater' ),
                    ['adjacentTo'] = STRING( 'WPN11' ),
                    ['color'] = STRING( 'ff0000ff' ),
                    ['type'] = STRING( 'Water Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 408.944, 12.5687, 82.5067 ),
                },
                ['Mass10'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.0174533, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 98.5, 18.3047, 304.5 ),
                },
                ['AMPN17'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AMPN06 AMPN08 AMPN18 AMPN19' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 136.781, 12.3403, 148.508 ),
                },
                ['Mass16'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.0174533, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 277.5, 20.9434, 164.5 ),
                },
                ['AirPN04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN00 AirPN06 AirPN09' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 45.28, 12.4848, 463.778 ),
                },
                ['Expansion Area 7'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.18326, 0.00226808, 0 ),
                    ['position'] = VECTOR3( 80.5, 18.7461, 90.5 ),
                },
                ['AMPN18'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AMPN06 AMPN07 AMPN08 AMPN17' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 78.1967, 18.719, 89.8309 ),
                },
                ['AirPN03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN08 AirPN09 AirPN02' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 76.7341, 18.6856, 87.6418 ),
                },
                ['Mass24'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.0174533, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 421.5, 18.1289, 435.5 ),
                },
                ['Transport Marker 09'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 184.246, 24.2305, 318.389 ),
                },
                ['Mass5'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.0174533, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 145.5, 20.6172, 368.5 ),
                },
                ['Transport Marker 00'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 325.459, 18.5974, 105.811 ),
                },
                ['Transport Marker 05'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 107.215, 17.86, 393.872 ),
                },
                ['ARMY_1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.0174533, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 148.5, 20.7168, 353.5 ),
                },
                ['Naval Link 07'] = {
                    ['color'] = STRING( 'ffff0000' ),
                    ['type'] = STRING( 'Naval Link' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 410.017, 15.1951, 108.766 ),
                },
                ['AMPN19'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AMPN13 AMPN16 AMPN17 AMPN20' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 210.5, 17.8242, 212.5 ),
                },
                ['AMPN02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AMPN01 AMPN09 AMPN11 AMPN12 AMPN03' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 232.919, 12.7092, 479.092 ),
                },
                ['WPN01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultWater' ),
                    ['adjacentTo'] = STRING( 'WPN00' ),
                    ['color'] = STRING( 'ff0000ff' ),
                    ['type'] = STRING( 'Water Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 98.0488, 12.5601, 412.473 ),
                },
                ['AirPN00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN01 AirPN04 AirPN06 AirPN09' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 136.777, 20.6406, 357.833 ),
                },
                ['Rally Point 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 129.5, 20.207, 371.5 ),
                },
                ['AirPN08'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN09 AirPN01 AirPN03 AirPN05' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 234.5, 17.5, 32.5 ),
                },
                ['Naval Link 12'] = {
                    ['color'] = STRING( 'ffff0000' ),
                    ['type'] = STRING( 'Naval Link' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 402.891, 14.4382, 270.324 ),
                },
                ['Mass19'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.0174533, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 321.5, 19.5078, 284.5 ),
                },
                ['AMPN07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AMPN06 AMPN18 AMPN08' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 20.1658, 12.6684, 20.1539 ),
                },
                ['AMPN11'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AMPN02 AMPN04 AMPN12 AMPN13' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 360.482, 12.413, 359.738 ),
                },
                ['Naval Link 09'] = {
                    ['color'] = STRING( 'ffff0000' ),
                    ['type'] = STRING( 'Naval Link' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 229.927, 13.559, 438.505 ),
                },
                ['Naval Link 00'] = {
                    ['color'] = STRING( 'ffff0000' ),
                    ['type'] = STRING( 'Naval Link' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 220.794, 15.834, 228.314 ),
                },
                ['Mass9'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.0174533, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 157.5, 20.8398, 277.5 ),
                },
                ['Expansion Area 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 176.5, 20.7402, 241.5 ),
                },
                ['Defensive Point 04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 106.5, 17.916, 75.5 ),
                },
                ['WPN03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultWater' ),
                    ['adjacentTo'] = STRING( 'WPN00 WPN06 WPN07' ),
                    ['color'] = STRING( 'ff0000ff' ),
                    ['type'] = STRING( 'Water Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 30.6223, 12.9052, 223.372 ),
                },
                ['Transport Marker 04'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 395.456, 17.6951, 111.446 ),
                },
                ['WPN08'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultWater' ),
                    ['adjacentTo'] = STRING( 'WPN04 WPN05 WPN11' ),
                    ['color'] = STRING( 'ff0000ff' ),
                    ['type'] = STRING( 'Water Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 479.5, 17.5, 297.5 ),
                },
                ['Mass20'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.0174533, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 190.5, 19.4063, 224.5 ),
                },
                ['ARMY_2'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.0174533, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 361.5, 20.7012, 156.5 ),
                },
                ['AMPN12'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AMPN02 AMPN03 AMPN04 AMPN11' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 431.496, 18.6332, 427.863 ),
                },
                ['LPN01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LPN00 LPN02 LPN03' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 152.712, 20.7672, 254.19 ),
                },
                ['AirPN02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN07 AirPN06 AirPN03' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 429.311, 18.6617, 426.405 ),
                },
                ['Mass23'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.0174533, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 437.5, 18.6602, 422.5 ),
                },
                ['Naval Area 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 395.5, 17.5, 397.5 ),
                },
                ['Mass22'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.0174533, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 71.5, 18.5215, 97.5 ),
                },
                ['Defensive Point 6'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 218.5, 20.668, 368.5 ),
                },
                ['WPN07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultWater' ),
                    ['adjacentTo'] = STRING( 'WPN03 WPN09' ),
                    ['color'] = STRING( 'ff0000ff' ),
                    ['type'] = STRING( 'Water Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 26.8299, 12.8619, 25.3539 ),
                },
                ['Naval Link 15'] = {
                    ['color'] = STRING( 'ffff0000' ),
                    ['type'] = STRING( 'Naval Link' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 140.708, 15.5045, 214.18 ),
                },
                ['Naval Link 14'] = {
                    ['color'] = STRING( 'ffff0000' ),
                    ['type'] = STRING( 'Naval Link' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 303.335, 14.3785, 381.884 ),
                },
                ['AirPN05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN01 AirPN08 AirPN07' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 475.717, 12.5983, 25.9999 ),
                },
                ['AMPN04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AMPN03 AMPN11 AMPN12 AMPN15 AMPN05' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 477.052, 12.6708, 227.029 ),
                },
                ['AMPN16'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AMPN14 AMPN15 AMPN19' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 240.38, 19.291, 159.739 ),
                },
                ['Naval Link 10'] = {
                    ['color'] = STRING( 'ffff0000' ),
                    ['type'] = STRING( 'Naval Link' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 81.4239, 13.858, 282.062 ),
                },
                ['WPN06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultWater' ),
                    ['adjacentTo'] = STRING( 'WPN03 WPN09' ),
                    ['color'] = STRING( 'ff0000ff' ),
                    ['type'] = STRING( 'Water Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 138.97, 12.2662, 149.965 ),
                },
                ['Mass21'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.0174533, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 88.5, 18.4004, 82.5 ),
                },
                ['Mass7'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.0174533, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 189.5, 24.2402, 319.5 ),
                },
                ['Transport Marker 01'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 411.311, 18.3571, 163.976 ),
                },
                ['Expansion Area 8'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 430.5, 18.6367, 427.5 ),
                },
                ['Naval Area 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 118.5, 17.5, 426.5 ),
                },
                ['Combat Zone 11'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 256.5, 17.5, 259.5 ),
                },
                ['LPN02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LPN00 LPN01 LPN04' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 256.363, 21.0593, 341.84 ),
                },
                ['Mass12'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.0174533, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 362.5, 20.6953, 169.5 ),
                },
                ['Rally Point 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 383.5, 19.5059, 133.5 ),
                },
                ['Defensive Point 5'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 140.5, 20.7012, 289.5 ),
                },
                ['AMPN10'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AMPN09 AMPN13 AMPN20' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 254.912, 21.0295, 345.464 ),
                },
                ['AirPN07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['adjacentTo'] = STRING( 'AirPN06 AirPN01 AirPN02 AirPN05' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 482.5, 17.5, 259.5 ),
                },
                ['AMPN08'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AMPN07 AMPN18 AMPN17 AMPN09 AMPN01' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 28.9463, 12.2133, 247.552 ),
                },
                ['Defensive Point 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 407.5, 17.7969, 438.5 ),
                },
                ['WPN02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultWater' ),
                    ['adjacentTo'] = STRING( 'WPN00 WPN04 WPN05' ),
                    ['color'] = STRING( 'ff0000ff' ),
                    ['type'] = STRING( 'Water Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0.139626, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 286.5, 17.5, 479.5 ),
                },
                ['AMPN01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AMPN02 AMPN09 AMPN08' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 24.8029, 12.5936, 482.788 ),
                },
                ['Mass17'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.0174533, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 355.5, 20.8242, 238.5 ),
                },
                ['AMPN15'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AMPN04 AMPN05 AMPN06 AMPN14 AMPN16' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 373.143, 20.4539, 138.133 ),
                },
                ['LPN03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['adjacentTo'] = STRING( 'LPN01 LPN04 LPN05' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 247.5, 20.5566, 165.5 ),
                },
                ['Naval Link 03'] = {
                    ['color'] = STRING( 'ffff0000' ),
                    ['type'] = STRING( 'Naval Link' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 236.193, 16.3734, 276.683 ),
                },
                ['Defensive Point 3'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 368.5, 20.7832, 227.5 ),
                },
                ['Protected Experimental Construction 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 124.5, 18.0098, 397.5 ),
                },
                ['WPN09'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultWater' ),
                    ['adjacentTo'] = STRING( 'WPN06 WPN07 WPN11' ),
                    ['color'] = STRING( 'ff0000ff' ),
                    ['type'] = STRING( 'Water Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 210.159, 12.7484, 34.8575 ),
                },
                ['Defensive Point 4'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 292.5, 20.707, 147.5 ),
                },
                ['AMPN14'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AMPN13 AMPN15 AMPN16' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 360.01, 20.7763, 255.639 ),
                },
                ['Mass6'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( -0.0174533, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 135.5, 20.6387, 355.5 ),
                },
                ['Naval Link 02'] = {
                    ['color'] = STRING( 'ffff0000' ),
                    ['type'] = STRING( 'Naval Link' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 289.502, 15.7926, 286.381 ),
                },
                ['Defensive Point 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 302.5, 17.957, 301.5 ),
                },
                ['Combat Zone 9'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 269.5, 20.375, 339.5 ),
                },
                ['Defensive Point 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 211.5, 17.834, 209.5 ),
                },
                ['AMPN20'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['adjacentTo'] = STRING( 'AMPN09 AMPN10 AMPN19' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0.000602126, 0 ),
                    ['position'] = VECTOR3( 158.458, 20.3968, 237.509 ),
                },
                ['Naval Defensive Point 00'] = {
                    ['color'] = STRING( 'ff0080FF' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Naval Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 163.5, 17.5, 449.5 ),
                },
                ['Naval Defensive Point 01'] = {
                    ['color'] = STRING( 'ff0080FF' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Naval Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 50.5, 17.5, 347.5 ),
                },
                ['Naval Defensive Point 02'] = {
                    ['color'] = STRING( 'ff0080FF' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Naval Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 437.5, 17.5, 121.5 ),
                },
                ['Naval Defensive Point 03'] = {
                    ['color'] = STRING( 'ff0080FF' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Naval Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 285.5, 17.5, 69.5 ),
                },
                ['Naval Defensive Point 04'] = {
                    ['color'] = STRING( 'ff0080FF' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Naval Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 91.5, 17.5, 146.5 ),
                },
                ['Naval Defensive Point 05'] = {
                    ['color'] = STRING( 'ff0080FF' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Naval Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 144.5, 17.5, 91.5 ),
                },
                ['Naval Defensive Point 06'] = {
                    ['color'] = STRING( 'ff0080FF' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Naval Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 360.5, 17.5, 423.5 ),
                },
                ['Naval Defensive Point 07'] = {
                    ['color'] = STRING( 'ff0080FF' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Naval Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 415.5, 17.5, 362.5 ),
                },
                ['Naval Rally Point 00'] = {
                    ['color'] = STRING( 'ff00FFFF' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Naval Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 368.5, 17.5, 370.5 ),
                },
                ['Naval Rally Point 01'] = {
                    ['color'] = STRING( 'ff00FFFF' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Naval Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 102.5, 17.5, 454.5 ),
                },
                ['Naval Rally Point 02'] = {
                    ['color'] = STRING( 'ff00FFFF' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Naval Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 389.5, 17.5, 42.5 ),
                },
                ['Naval Rally Point 03'] = {
                    ['color'] = STRING( 'ff00FFFF' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Naval Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 137.5, 17.5, 138.5 ),
                },
                ['Rally Point 02'] = {
                    ['color'] = STRING( 'FF808000' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 286.5, 18.873, 320.5 ),
                },
                ['Rally Point 03'] = {
                    ['color'] = STRING( 'FF808000' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 220.5, 18.4121, 201.5 ),
                },
                ['Rally Point 04'] = {
                    ['color'] = STRING( 'FF808000' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 194.5, 19.1035, 224.5 ),
                },
                ['Rally Point 05'] = {
                    ['color'] = STRING( 'FF808000' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 314.5, 18.6602, 291.5 ),
                },
                ['Rally Point 06'] = {
                    ['color'] = STRING( 'FF808000' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 416.5, 18.1934, 414.5 ),
                },
                ['Rally Point 07'] = {
                    ['color'] = STRING( 'FF808000' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 91.5, 18.7363, 105.5 ),
                },
            },
        },
    },
    Chains = {
        ['New Chain 00'] = {
            Markers = {
                "Naval Link 00",
                "Naval Link 01",
                "Naval Link 02",
                "Naval Link 03",
            },
        },
        ['New Chain 01'] = {
            Markers = {
                "Naval Link 05",
                "Naval Link 04",
                "Naval Link 06",
                "Naval Link 07",
                "Naval Link 08",
                "Naval Link 09",
                "Naval Link 10",
                "Naval Link 11",
                "Naval Link 12",
                "Naval Link 13",
                "Naval Link 14",
                "Naval Link 15",
            },
        },
    },
    --[[                                                                           ]]--
    --[[  Orders                                                                   ]]--
    --[[                                                                           ]]--
    next_queue_id = '1',
    Orders = {
    },
    --[[                                                                           ]]--
    --[[  Platoons                                                                 ]]--
    --[[                                                                           ]]--
    next_platoon_id = '1',
    Platoons = 
    {
    },
    --[[                                                                           ]]--
    --[[  Armies                                                                   ]]--
    --[[                                                                           ]]--
    next_army_id = '6',
    next_group_id = '4',
    next_unit_id = '53',
    Armies = 
    {
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_1'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_2'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_9'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['UNIT_48'] = {
                                type = 'uel0104',
                                orders = '',
                                platoon = '',
                                Position = { 423.500000, 18.685547, 420.500000 },
                                Orientation = { 0.000000, 14.355335, 0.000000 },
                            },
                            ['UNIT_52'] = {
                                type = 'ueb2301',
                                orders = '',
                                platoon = '',
                                Position = { 84.500000, 18.820313, 92.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_47'] = {
                                type = 'ueb3101',
                                orders = '',
                                platoon = '',
                                Position = { 84.500000, 19.031250, 98.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_49'] = {
                                type = 'ueb3101',
                                orders = '',
                                platoon = '',
                                Position = { 425.500000, 18.886719, 417.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_45'] = {
                                type = 'uel0104',
                                orders = '',
                                platoon = '',
                                Position = { 86.500000, 18.937500, 95.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_51'] = {
                                type = 'ueb2301',
                                orders = '',
                                platoon = '',
                                Position = { 425.500000, 18.662109, 423.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_46'] = {
                                type = 'ueb1101',
                                orders = '',
                                platoon = '',
                                Position = { 84.500000, 18.964844, 96.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_50'] = {
                                type = 'ueb1101',
                                orders = '',
                                platoon = '',
                                Position = { 425.500000, 18.796875, 419.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['NEUTRAL_CIVILIAN'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['UNIT_31'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 417.500000, 18.308594, 425.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_5'] = {
                                type = 'uec1201',
                                orders = '',
                                platoon = '',
                                Position = { 419.500000, 18.400391, 422.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_12'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 81.500000, 18.871094, 100.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_21'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 92.500000, 18.412109, 90.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_40'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 428.500000, 18.876953, 417.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_24'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 93.500000, 18.363281, 92.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_32'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 418.500000, 18.328125, 425.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_36'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 427.500000, 19.000000, 414.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_11'] = {
                                type = 'uec1201',
                                orders = '',
                                platoon = '',
                                Position = { 90.500000, 18.644531, 93.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_16'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 84.499947, 19.074215, 101.486908 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_37'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 428.500000, 18.910156, 416.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_13'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 81.500000, 18.880859, 99.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_14'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 81.500000, 18.882813, 98.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_15'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 81.500053, 18.847252, 101.513092 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_19'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 90.500000, 18.535156, 90.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_30'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 416.500000, 18.283203, 425.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_26'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 416.500000, 18.263672, 422.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_18'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 83.499985, 19.005909, 101.495636 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_34'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 425.500000, 19.046875, 414.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_22'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 93.500000, 18.349609, 90.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_27'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 416.500000, 18.277344, 423.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_29'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 419.500000, 18.357422, 425.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_33'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 428.500000, 18.966797, 414.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_28'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 416.500000, 18.281250, 424.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_20'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 91.500000, 18.474609, 90.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_35'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 426.500000, 19.027344, 414.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_23'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 93.500000, 18.355469, 91.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_17'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 82.500015, 18.925680, 101.504364 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_25'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 93.500000, 18.376953, 93.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_39'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 428.500000, 18.939453, 415.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
    },
}
